### ISSUE TITLE
JSON odziv v AttemptViewSet.submit

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#10]
Strežnik bi Python skripti vrnil seznam popravljenih Attemptov (predvsem popravil `valid` in še kaj dodal v `feedback`). Če vrnem samo seznam Attemptov, stvar ne dela, ker jih ne spravi v JSON, zato na roke naredim slovarje, ki gredo skozi. Verjetno se to da narediti avtomatično?

**Comment by gregorjerse** [comment]
Da se. Glej moj pull request (ga lahko vežem na issue?)

**Comment by matijapretnar** [comment]
Super. Pull request omeniš z #12. V commitu (lahko v tistem za merge) pa lahko napišeš closes #št.issueja, da se issue zapre.
