### ISSUE TITLE
Vidnost rešitev

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#100]
Predlagam:
* spremeni se komentar iz "Uradne rešitve so pogojno vidne" v "Uradne rešitve vidne po sprejeti r."
* Ko urejamo sklop (klik na zobnik), je možno tam nastaviti vidnost rešitev (kot je pri samem vnosu)

**Comment by lokarM** [comment]
Iz anket je dobra ideja:
* da bi bilo možno nastaviti, da so rešitve vidne po n neuspešnih poskusih (n naj bi nastavil učitelj)
* da bi bile rešitve vidne od določenega dneva dalje (določenega kot datum ali pa m dni po objavi naloge)

**Comment by matijapretnar** [comment]
Prvi del bomo rešili, drugega pa v #103.

**Comment by matijapretnar** [comment]
Urejeno.

Closed by 245a64b and 913054e
