### ISSUE TITLE
import

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#101]
Če sestavljalec naloge predvidi

          import random

študent pa rešitve napiše z 

         from random import *

tega testni program "ne preživi" (glej npr. [https://www.projekt-tomo.si/problems/173/solutions/79](https://www.projekt-tomo.si/problems/173/solutions/79)

**Comment by matijapretnar** [comment]
Da, to je zato, ker je testni program

```python
import random

koliko = random.randint(10, 20)
vzorec = '* ' * koliko
print(vzorec)
odg = int(input('Koliko * vidite: '))
if odg == koliko:
    print('Vaš vid je še dober.')
else:
    print('Prosim, zglasite se pri okulistu Tonetu.')

Check.part()
random.seed(100)
with Check.input(['12']):
    Check.output(Check.current_part['solution'], [
    '* * * * * * * * * * * * ',
    'Koliko * vidite: 12',
    'Vaš vid je še dober.'
])

with Check.input(['12']):
    Check.output(Check.current_part['solution'], [
    '* * * * * * * * * * * * * * * * * ',
    'Koliko * vidite: 12',
    'Prosim, zglasite se pri okulistu Tonetu.'
])
```

torej kliče `random.seed`. In če študent tega ne uvozi, bo seveda prišlo do napake. Teste je treba napisati tako, da se ne zanašajo na oddano rešitev, npr. da še enkrat uvozijo `random`:

```python
Check.part()
import random
random.seed(100)
...
```
