### ISSUE TITLE
Dokumentacija za podporo novih jezikov

### ISSUE THREAD

**Issue by mrcinv** [matijapretnar/projekt-tomo#102]
Fino bi bilo imeti dokumentacijo, kako se dodaja podporo za nove jezike. Sam bi rad dodal nov jezik octave. Kam naj pogledam, kako se to naredi.

**Comment by matijapretnar** [comment]
Podporo se da dodati na cel kup načinov, odvisno od jezika, zato bi bilo po mojem najbolje, če se enkrat dobiva v živo. Pošljem mail.
