### ISSUE TITLE
Premikanje vrstnega reda

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#104]
Po zadnjih popravkih ob poskusu spreminjanja vrstnega reda nalog dobimo Server error 500

**Comment by lokarM** [comment]
To se dogaja tako na nivoju predmeta kot na nivoju posamezne naloge. 

Ali je možno, da bi zadevo kmalu rešili, ker je načeloma "nujno", da je vrstni red za študente "pravi".

**Comment by nbasic** [comment]
Tudi jaz dobivam Server Error (500): https://www.projekt-tomo.si/problem_set/66/move/

Se strinjam, da bi ta bug moral imeti največjo prioriteto.

**Comment by matijapretnar** [comment]
Težava je bila v tem, da je neka koda nehala delovati v Djangu 1.9. Zaenkrat sem stvari rešil tako, da sem zamrznil uporabljene verzije paketov. Bi bil pa izjemno vesel, če bi mi pri reševanju problemov pomagal še kdo.
