### ISSUE TITLE
Štetje pravilnosti

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#105]
Ne vem, ali nečesa ne razumem prav: Sumarni podatki se bistveno razlikujejo od podrobnih:

![tomo-problem](https://cloud.githubusercontent.com/assets/11019265/12349624/6717dd4e-bb71-11e5-84f1-c572c1a0e537.png)

Klik pa da

![tomo-problem-2](https://cloud.githubusercontent.com/assets/11019265/12349629/7104bfc0-bb71-11e5-9890-361968e7703c.png)

Kaj torej pomeni tistih 17 pravilnih?

**Comment by nbasic** [comment]
Tudi jaz sem se že večkrat spraševal, kaj te številke pravzaprav pomenijo ...

**Comment by matijapretnar** [comment]
Te številke so bile procenti. Zdaj spet kaže število oddanih rešitev. Poleg tega je prikaz le za opazovane študente.
