### ISSUE TITLE
Težave z brskalnikom Edge

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#108]
Če se z Microsoft Edge prijavimo direktno na http://www.projekt-tomo.si, dobimo "solato"

![image](https://cloud.githubusercontent.com/assets/11019265/13426920/f3dcca92-dfb0-11e5-84b0-aa360246d9d3.png)

Če gremo na https://www.projekt-tomo.si, je ok!

**Comment by matijapretnar** [comment]
To je videti podobno kot #72, tako da bom ta issue zaprl in ga obnovil v #72.
