### ISSUE TITLE
Preverjanje

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#109]
Naloga zahteva, da vrnemo množico /Sestavite funkcijo `ustrezljivi(oseba, d)`, ki sprejme ime osebe ter slovar zaljubljenih, vrne pa _množico_ vseh ljudi, ki so do dane osebe še posebej ustrežljivi. /

testi so:

Študent(ka) je napisala enostavno 

def ustrezljivi(oseba, d):
    return None

Pri preverjanju ji potem Tomo napiše

Traceback (most recent call last):

        File "/home/zigazupancic/Documents/tina/ljubezen_nam_je_vsem_v_pogubo_ii.py", line 598, in _validate_current_file

          'Eva' : {'Bine'}})))

      TypeError: 'NoneType' object is not iterable

**Comment by matijapretnar** [comment]
Ne vem, meni javi običajno napako:

  - Izraz ustrezljivi('Cene', {'Ana' : {'Bine', 'Cene'},
                                           'Bine' : {'Ana'},
                                           'Cene' : {'Bine'},
                                           'Davorka' : {'Davorka'},
                                           'Eva' : {'Bine'}})
     vrne None namesto {'Bine', 'Eva', 'Cene', 'Ana'}.
  - Izraz ustrezljivi('Cene', {}) vrne None namesto set().
  - Izraz ustrezljivi('Cene', {'Ana' : {'Bine', 'Cene'},
                                           'Bine' : set(),
                                           'Cene' : {'Bine'},
                                           'Davorka' : {'Davorka'},
                                           'Eva' : {'Bine'}})
     vrne None namesto {'Ana'}.

Lahko da so se vmes testi spremenili.
