### ISSUE TITLE
čšž pri imenih uporabnikov

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#113]
Slika pove vse ;-)

![image](https://cloud.githubusercontent.com/assets/11019265/15929199/db233e48-2e4b-11e6-8684-dd4e7e1e43f8.png)

Ampak pri "starem" predmetu Programiranje 1 pri študentih teh težav ni!

![image](https://cloud.githubusercontent.com/assets/11019265/15929232/16ef37e2-2e4c-11e6-822c-54e758c193b9.png)

**Comment by lokarM** [comment]
Ampak da je zadeva še bolj "zanimiva", so lahko č-ji OK, ali pa ne - morda je zadeva povezana s tem od kje (AAI / Google / FB) prihaja prijava 

![image](https://cloud.githubusercontent.com/assets/11019265/15929313/a0fe17c8-2e4c-11e6-9632-92a061a4be49.png)

**Comment by matijapretnar** [comment]
Videti je, kot da je na strani šole narobe nastavljen vnos v ArnesAAI.

**Comment by matijapretnar** [comment]
To bomo reševali v okviru #119.
