### ISSUE TITLE
Podpora za macOS

### ISSUE THREAD

**Issue by MaticConradi** [matijapretnar/projekt-tomo#136]
Kako je s podporo za macOS?

**Comment by lokarM** [comment]
Ne razumem. Moji študenti veselo uporabljajo (vsaj za 4 vem) MACe ...

**Comment by MaticConradi** [comment]
Pri reševanju vedno naletimo na tole napako.
![screen shot 2017-02-14 at 19 29 50](https://cloud.githubusercontent.com/assets/5693961/22942989/0770c514-f2ec-11e6-9c20-d8248389a57a.png)

**Comment by matijapretnar** [comment]
Ali mi lahko prosim po e-mailu pošljete problematično datoteko? Načeloma bi zadeva morala delati neodvisno od operacijskega sistema, lahko pa pride do kakšnih manjših razlik.

**Comment by matijapretnar** [comment]
Težava zna biti v nameščenih certifikatih. Na https://www.python.org/downloads/release/python-360/ piše:

> macOS users: If you are using the Python 3.6 from the python.org binary installer linked on this page, please carefully read the Important Information displayed during installation; this information is also available after installation by clicking on /Applications/Python 3.6/ReadMe.rtf. There is important information there about changes in the 3.6.0 installer-supplied Python, particularly with regard to SSL certificate validation.

**Comment by MaticConradi** [comment]
Izgleda da to reši problem.
