### ISSUE TITLE
Dokumentacija

### ISSUE THREAD

**Issue by gregorjerse** [matijapretnar/projekt-tomo#14]
Živjo!

Kaj praviš na to, da bi kodo malo bolje podokumentirali? Jaz predlagam, da bi uporabili Sphynx. Je pa res, da je s tem kar nekaj dela.

**Comment by matijapretnar** [comment]
Po mojem koda sama ni tako zelo zanimiva, da bi jo bilo vredno komentirati. Ja, če je kaj zapletenega, potem že, ampak sicer pa s tem ne bi izgubljal časa.
