### ISSUE TITLE
Prikazovanje pravilnosti pri pregledu rešitev

### ISSUE THREAD

**Issue by jaanos** [matijapretnar/projekt-tomo#140]
Lepo bi bilo, če bi se pri pregledu rešitev zraven izpisalo, ali je rešitev pravilna ali ne (npr. zelen ali rumen krogec). Dogaja se mi namreč, da kliknem na nekoga, ki naj bi narobe rešil, pa potem vidim pravilno rešitev (ker je vmes že popravil), pa se sprašujem, zakaj je to narobe:)

**Comment by matijapretnar** [comment]
Ja, smiselno. Sem mislil, da to že delamo, pa očitno ne :)

**Comment by lokarM** [comment]
Aha ti misliš, da naj bi takrat, ko kliknemo na pregled kode, ob kodi bilo označeno, ali je rešitev pravilna, ali ne ...

**Comment by jaanos** [comment]
Tako, ja.

**Comment by jaanos** [comment]
Zaprto s #141.
