### ISSUE TITLE
Skrčen izpis študentov

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#143]
Dobil sem naslednjo željo:

_V spletni učilnici ne rešujejo vsi dijaki vseh nalog. Pri vsaki nalogi pa se "zvrstijo" vsi. Bi bilo možno, da bi se pri posamezni nalogi pokazali samo dijaki, ki so to nalogo reševali (npr. tisti, ki so si jo prenesli).....?_

Če prav razumem, bi učitelj rad, da ko kliknemo na posamezno nalogo, dobimo spisek le tistih dijakov/študentov, ki so nekaj počeli s to nalogo (jo prenesli, jo reševali ...)

**Comment by jaanos** [comment]
V starem Tomu je bila možnost prikaza samo tistih rešitev, ki so se zgodile v določenem času (če se prav spomnim, so bile možnosti pol ure, dve uri, en teden, eno leto in vse). Mogoče bi lahko imeli zdaj nekaj podobnega (treba bi sicer bilo dobit še podatek o tem, kdaj je bila podnaloga nazadnje prenesena).

To bi tudi rešilo problem, kaj naredit s starimi študenti - tako jih privzeto enostavno ne bo prikazalo, čeprav so njihove rešitve lahko še vedno v sistemu.
