### ISSUE TITLE
Organizacija nalog

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#17]
Ugotoviti bo treba, kako bi organizirali naloge. Nekaj idej:
* Po mojem bi bilo dobro, da bi naloge lahko ustvarjal vsak, saj se nam s tem zna zgoditi, da stvar precej bolj zaživi. Kot je že Gregor rekel, bi bilo dobro (in tudi enostavno), da bi ljudje o nalogah lahko glasovali o kvaliteti in zahtevnosti. S tem bi lahko verjetno tudi ob morebitni poplavi nalog poskrbeli, da bodo dobre vidne.
* Glede deljenja nalog bi lahko naredili tako: vsaka naloga ima tudi neobvezen `ForeignKey` za starša in vsakič, ko nalogo od nekod prekopiraš, se ta starš nastavi. Nato vsakič, ko se starša popravi, dobiš obvestilo: "Starš je popravljen, ali želiš posodobiti svojo nalogo?" Potem pa lahko rečeš, "ja" (in se izvede nek merge?), "ne", ali pa "nehaj mi težiti" in naloga postane samostojna. S tem bi dosegli to, da ljudje ne urejajo nalog drugih, hkrati pa ne bi divergirale.
* Nalogam bi bilo treba dati značke. Ko gledam naloge pri Uvodu v programiranje, vidim, da je nastala cela štala, ker je cel kup nalog s kvizov, kolokvijev, poskusnih izpitov, vse seveda v 4 skupinah, ampak za nobeno nalogo ne veš, ali je z datotekami, nizi…
* S temi značkami bi lahko načeloma naredili tudi predmete. Da bi res lahko delali predmete, bi bilo dobro narediti še to, da so nekatere značke rezervirane in jih ne more dodati kar vsak, temveč samo posvečeni. Prav tako bi bilo dobro, da ti posvečeni lahko urejajo tudi tuje naloge. Mogoče bi vseeno naredili tako kot zdaj?

@sonjajerse in @gregorjerse, kaj mislita?

**Comment by matijapretnar** [comment]
Za mnenje sprašujem še @lokarM, zdaj, ko je prišel na GitHub.

**Comment by lokarM** [comment]
Če bo naloge lahko ustvarjal kdorkoli, je verjetno dobro, da ima vsak uporabnik, ki ustvarja nalogo, takrat dodeljen predmet - recimo kar NalogeUpoIme - in se naloge ustvarjajo tam. Kasneje pa se lahko te naloge prekopira v "prave" predmete. Za prave predmete - recimo Programiranje1-201415 pa bi moral poslati zahtevo administratorju, da mu ga dodeli. Del zahteve bi moral biti tudi namen predmeta (npr. Javni tečaj za vse, ki se prvič srečujejo s programskim jetzikom Python, predmet Osnove programiranja za ... )

Potem potrebujemo različne pravice nad nalogami:
- javno (privzeto): vsak vidi nalogo in jo lahko rešuje in tudi kopira
- pooblaščeno: uporabnik lahko pooblasti določene uporabnike, da lahko kopirajo njegove naloge (vse, nekatere, vse v predmetu???)
- privatno: naloge so sicer vidne vsem, a jih lahko le rešujejo, ne morejo pa jih kopirati

Značke: mislim, da je smislena in nujna vpeljava. Fino je, da se uporabniku, ki ustvari nalogo, že vnaprej ponudi nabor "fiksnih" značk - da ne bomo imeli značk "zanka", "zanke", ... 

Tisto s ForeignKey se mi zdi smiselna rešitev. Še vedno pa bi bilo morda smiselno, da bi naloga potem ne postala čisto samostojna, ampak bi si še vedno zapomnila, da je bila enkrat izpeljana iz te in te naloge. To bi prišlo prav pri iskanju, ko bi lahko rekel, da naj pokupčka naloge, ki so bile včasih v relaciji ...

**Comment by gregorjerse** [comment]
Še mojih 5 centov.
* Značke se mi zdijo super. Ampak ne bi uporabnikom dovolil ustvarjati svojih značk, temveč bi jih dodal po zdravi pameti. Več ali manj bi jih imel za težavnost in tip nalog. Vsaj zaenkrat.
* Glede staršev: jaz se z mergom ne bi ukvarjal. Zelo težko je dobro narediti GUI za to, še težje pa uporabnikom dopovedati kaj se dogaja. Pa tudi kdaj in kako bi ga obvestil, da se je starš spremenil? Kaj boš naredil z nalogo v časo, ko je starš spremenjen pa uporabnik še ni odgovoril? In podobno...
Naj bodo stvari enostavne. Nalogo lahko uvrstiš v obliki kot je v katerikoli predmet/sklop... (modulo pravice). Če se naloga spremeni, se spremeni. Če kopiraš nalogo, potem narediš kopijo. 
Starša si jaz ne bi zapomnil v obliki ForeignKey, ker se mi zdi v bazi grdo imeti ForeignKey, ki je lahko Null (in je potem to treba povsod preverjati). Raje bi za vsako nalogo imel seznam, imenujno ga viri, kjer bi avtor lahko naštel naloge, s katerimi si je pomagal pri izdelavi le-te. Seveda bi ob kopiranju naloge le-to avtomatsko uvrstil v vire kopije.
* Naloge naj lahko ustvarja vsak. Morda je tudi smiselno, da naloge niso nujno v predmetih, ampak lahko živijo svoje življenje izven predmetov. Uvrstimo jih lahko pod "Neuvrščene naloge"? 
* @lokarM : s pravicami bi jaz čimmanj kompliciral. V grobem za vsako nalogo (kot vidim jaz) obstajajo naslednje pravice.
  * nič: očitno.
  * reševanje: ogled + prenos datoteke z nalogami na svoj računalnik. To bi sicer lahko razbili na ogled (samo ogled nalog preko web) in reševanje (prenos datoteke, reševanje), samo v tem ne vidim smisla.
  * polno: ogled avtorjeve kode za nalogo.
Pravice lahko nastavimo na posamezno nalogo.
* Predmete bi sicer implementiral kot značke, ampak bi ločil med predmeti in splošnimi značkami. Morda bi bilo za razmisliti ali potrebujemo poleg značke tudi kakšen dotaten podatek. Recimo pri težavnosti imamo lahko več značk (lahka, srednja, težka, zelo težka...), ali pa značko težavnost + število od 1 do 5...

**Comment by lokarM** [comment]
* Mislim, da je nujno imeti evidenco nad izpeljanimi zadevami. Ko kot učitelj uporabljaš zadeve, se ti večkrat zgodi, da imaš pri različnih predmetih isto nalogo in odkriješ napako. Zoprno je, da jo moraš sedaj popravljati povsod in ne le na enem mestu. Poleg tega - poglej obstoječe stanje. Ista naloga se pojavlja "ogomnokrat" v različnih predmetih. In če bomo potem anredili iskanje (npr. po značkah), bo prvih 10 zadetkov kopija iste naloge. 
* s pravicami bo potrebno nekaj narediti. Namreč tvoj predlagani sistem ne omogoča ločitve med predavatelji in študenti. Kako naj npr. "dovolim", da moje naloge kopiraš le ti in nihče drug. Drugače pač študent enostavno "skopira" nalogo in ima dostop do rešitve. Če pa preprečim kompiranje, je ne more skopirati "pravi" predavatelj
* strinjam se, da bi bile značke "zaprte". Morda bi bilo dobro le, da bi bilo možno predlagati novo značko, ki pa jo potem upravljalec sistema doda (ali pa ne).
* Mislim, da ni dobro, da bi vsak lahko ustvarjal predmete. Enostavno jih bo potem preveč in ne bo pregledno. Že sedaj (pa je zadeva omejena) jih je veliko (pa tudi če pozabimo na to, da so ves čas "odprte" vse naloge v sklopu predmeta).

**Comment by gregorjerse** [comment]
* Moj predlog evidenco vsekakor vsebuje, samo da je zapisana na drugačen način.
* Sistem to omogoča, morda nisem bil dovolj jasen. Pravica je trojica kdo, kaj, kje. Torej lahko na vsakem objektu nastaviš pravice vsakemu uporabniku, če seveda želiš (ali skupini ali...).

**Comment by matijapretnar** [comment]
A bi zadeve prediskutirali v živo ta torek, 3. marca, ob 11h?

**Comment by lokarM** [comment]
Lahko. RAčunam, da bom takrat že v Ljubljani, ker imam ob 9h nujne opravke v Kranju. Ampak računam, da ne bodo trajali več kot uro.

**Comment by matijapretnar** [comment]
To temo bom razdelil na manjše podteme.
