### ISSUE TITLE
Stran za prijavo

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#18]
Ko prideš na osnovno stran, se ti prikaže obrazec za prijavo, če nisi prijavljen, in seznam nalog, če si. Če se prijaviš napačno, greš nazaj na obrazec za prijavo z opozorilom.

**Comment by lokarM** [comment]
Verjetno se ti prikaže seznam predmetov  in ne seznam nalog

**Comment by matijapretnar** [comment]
Ne, na prvih vajah je dovolj, da se ti prikaže seznam nalog :smile: Na drugih se bo prikazal seznam sklopov, na neki točki pa seznam predmetov. Trenutno je bolj pomembno, da čimprej naredimo stvari, ki jih potrebujemo za prve vaje.

**Comment by sonjajerse** [comment]
Živjo! Obrazec za prijavo trenutno še ni čisto v skladu z Bootstrapom, ker mi ni uspelo dobro namestiti dodatka django-bootsrap3. Ko sem to aplikacijo dopisala v INSTALLED_APPS, se strežnik ni hotel več zagnati. Zato sem kodo, ki uporablja ta dodatek, zakomentirala in pustila delujočo prejšnjo verzijo (pri kateri input elementi niso razreda form-control).

**Comment by matijapretnar** [comment]
* polje za geslo mora imeti `type="password"`, da se ne vidi vnosa
* pogled `welcome` ne spada v aplikacijo `problems`, temveč v `users`
* tega pogleda v resnici ne rabiš, ker lahko uporabiš vgrajeni Djangov pogled (poglej prosim v staro kodo, kako se to naredi)

**Comment by matijapretnar** [comment]
To sem zdaj popravil, bi bilo pa lepo imeti na vrhu neko navigacijo, v kateri bo gumb za odjavo. Trenutno predpostavljamo, da anonimnih uporabnikov ni in so vsi prijavljeni.

**Comment by sonjajerse** [comment]
Bo narejeno do jutri zjutraj.

**Comment by sonjajerse** [comment]
Link za odjavo je narejen. Navigacije še ni (premalo strani zaenkrat).

**Comment by matijapretnar** [comment]
Closed by #276d9f
