### ISSUE TITLE
Primerjava z uradno rešitvijo

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#20]
Tabelica, v katerem lahko vsak del rešitve primerjaš z uradno rešitvijo. Za prve vaje bo dovolj, da se primerjava pokaže, če je tvoja rešitev pravilna.

**Comment by sonjajerse** [comment]
Trenutno comitana stran še ne deluje pravilno. Nisem še poskrbela za primere, ko uporabnik še ni rešil vseh delov naloge.
