### ISSUE TITLE
Prikaz pravilnosti rešitev

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#21]
To, da se ob vsakem delu naloge vidi, ali je pravilno rešena ali ne.

**Comment by sonjajerse** [comment]
Tu misliš na glifikone?

**Comment by matijapretnar** [comment]
Ja, pa verjetno še malo barve.

**Comment by sonjajerse** [comment]
Koda (še) ni komentirana, zato bom za začetek napisala sem:
- če so rešitve vseh podnalog sprejete, se naslov naloge obarva zeleno
- če katera od rešitev podnalog ni sprejeta, se naslov obarva rdeče
- če je nekaj rešitev podnalog sprejetih in nobena rešitev podnalog ni zavrnjena, se naslov obarva rumeno

Se strinjata s tako razdelitvijo?

Glifikona tumbs-up in thumbs-down sta zaenkrat živo zelene in živo rdeče barve. Z Gregorjem misliva, da bo lepše izgledalo (bolj barvno usklajeno), če bosta barvi enakega odtenka kot barva naslova naloge. Te barve so bolj umirjene, zato bi v tem primeru verjetno za malenkost povečala ikoni, da bosta bolj vidni.

Gregor predlaga, da v model dodamo metode, ki povejo, ali je naloga v celoti sprejeta, delno sprejeta ali zavrnjena (isti kriteriji, kot za obarvanje). To nam bo olajšalo delo, ko bomo ugotavljali, ali je cel odsek sprejet (mogoče tudi cel predmet?).

**Comment by matijapretnar** [comment]
Ja, se strinjam z vsem.
