### ISSUE TITLE
Izgled sklopov

### ISSUE THREAD

**Issue by gregorjerse** [matijapretnar/projekt-tomo#25]
Za sklope predmeta sem sedaj dodal nek izgled v vejo assembly_progress . Prosim preglejte in podajte komentarje.

**Comment by matijapretnar** [comment]
Meni se tisto oranžno včasih pobarva, včasih pa ne. A kaj veš, zakaj?

**Comment by gregorjerse** [comment]
Kaj je 'tisto oranzno'? Lahko pripnes screenshot, nisem preprican da vidis isto kot jaz.

Progress bar se sicer izrise preko javascript metode, lahko da je tam kaksen hrosc. Koda je na hitro shekana skupaj samo za to, da se pogleda izgled. Pripenjam screenshot mojega brskalnika.

![progress](https://cloud.githubusercontent.com/assets/4426582/6835761/23fdb618-d33d-11e4-8eb6-837fb96ccf13.png)

**Comment by matijapretnar** [comment]
No, pri meni je večino časa videti takole:
![screen shot 2015-03-26 at 21 16 01](https://cloud.githubusercontent.com/assets/1502128/6856029/626a12aa-d3fd-11e4-8641-85a352509cf3.png)

Drugače so mi pa všeč taki enobarvni, npr spodnji na 
![pure-css-radial-progress-bar](https://cloud.githubusercontent.com/assets/1502128/6856087/c143bfb0-d3fd-11e4-9647-8d2122934115.jpg)
Samo barve bi dal kar tiste od bootstrapa, danger za < 50%, success za >90% in warning vmes. Noter pa napisane procente.

Lahko bi ponucali: http://codepen.io/shankarcabus/pen/GzAfb, http://codepen.io/cliffpyles/pen/xbsiC ali http://codepen.io/jo-asakura/pen/stFHi/

**Comment by matijapretnar** [comment]
Zaenkrat sem pustil samo tekst. Zaradi bledih barv se na študentskih računalnikih skoraj nič ne vidi. Naredil sem rebase `assembly_progress` na `master`, zato povozi svojo vejo, ko naslednjič delaš.

**Comment by matijapretnar** [comment]
Na neki točki bi bilo lepo imeti kakšen lepši prikaz procentov, ampak zaenkrat je to, kar je, v redu.
