### ISSUE TITLE
Logo za mobilno aplikacijo

### ISSUE THREAD

**Issue by sonjajerse** [matijapretnar/projekt-tomo#26]
Prilagam dva primera logotipa za mobilno aplikacijo.

Zgledovala sem se po izgledu napisa Tomo v navigacijski vrstici v starem in novem Tomotu.

Meni je lepši črno-beli napis, ker bolj izstopa. Če izberemo tega, predlagam, da ustrezno obarvamo tudi navigacijo v novem Tomotu, da bo izgled "logotov" enak za mobilno in spletno aplikacijo.

![logo_sivi](https://cloud.githubusercontent.com/assets/10705598/6867178/cdb0e598-d47f-11e4-9c0a-8086cf4a30d6.png)

![logo_crni](https://cloud.githubusercontent.com/assets/10705598/6867183/d982898a-d47f-11e4-8c50-47bc9199f49d.png)

**Comment by matijapretnar** [comment]
Sem za črno varianto. Kerning je videti napačen, saj sta T in o preveč blizu. Ampak zaenkrat naj bo. Bi pa potem res tudi navigacijo dal na črno. In ko že popravljaš navigacijo, ali lahko še daš, da je vedno vidno. To je koristno predvsem zato, da lahko vedno vidiš, kako je študentu ime, če ima odprt brskalnik.

**Comment by matijapretnar** [comment]
Navbar ne paše sem, bom odprl nov issue. Logo je v redu.
