### ISSUE TITLE
Pravice

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#28]
V modelu `Course` imamo polje `teachers`, vendar se nikjer ne uporablja. Zaenkrat preverjamo, ali ima oseba status administratorja. To bo treba popraviti. @gregorjerse & @sonjajerse, to se verjetno preverja v viewu? S čim pa?

**Comment by matijapretnar** [comment]
V `utils` sem dodal metodo `verify(cond)`, ki sproži napako HTTP 403 (Permission denied), če pogoju ni zadoščeno. Tako lahko v pogledu pokličemo npr `verify(request.user.ima_pravico_do_naslednjega_dejanja)`.

**Comment by matijapretnar** [comment]
V modelu User je treba dodati še nadaljnje pravice, npr. `can_view_problem`, itd.

**Comment by gregorjerse** [comment]
Je to ze reseno?

**Comment by matijapretnar** [comment]
Da, načeloma je to zdaj rešeno.
