### ISSUE TITLE
Učiteljev uporabniški vmesnik

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#31]
Pripravil sem kodo za premikanje nalog v sklopu in sklopov v predmetu. Podobno bom naredil tudi skrivanje nalog in rešitev. @sonjajerse, a lahko narediš smiselne gumbke v HTML-ju? Po mojem je najbolje, da se v ustrezni view doda bool `show_teacher_controls` ali kaj takega, pa potem odvisno od tega pokažeš varianto.

**Comment by gregorjerse** [comment]
Je to ze zaprto?

**Comment by matijapretnar** [comment]
Bom zaprl in odprl issue za posamezne manjkajoče stvari.
