### ISSUE TITLE
Spisek manjkajoče funkcionalnosti

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#32]
Tule bi napisal stvari, ki jih stari Tomo ima, novi pa še ne, vendar smo še preveč leni, da bi odprli issue, ali pa moramo razmisliti, ali jih sploh hočemo. Ko bomo vse našteli in za vse odprli issue, lahko tole zapremo.

Za začetek:
* statistika
* naprednejši testi v Pythonu
* podpora za R in infrastruktura za ostale programske jezike
* prijava na predmete
* datoteka z zgodovino
* datoteke za preverjanje na MOSSu
* datoteke za masovno ocenjevanje (ni besedil nalog, samo vse rešitve, v komentarjih pa javljene napake)
* kopiranje nalog
* urejanje in dodajanje nalog preko lastnega uporabniškega vmesnika (ne django admina)
* pop-up prikaz rešitev
* anonimni problemi

**Comment by lokarM** [comment]
* statistika [DA, po možnosti še razširjeno]
* naprednejši testi v Pythonu [DA, po možnosti še razširjeno]
* podpora za R (?) in infrastruktura za ostale programske jezike (v torek se menimo glede C#)
* prijava na predmete  [ne vem kaj točno misliš - ali to, da se mora študent odločiti, katere predmete vidi - če to, DA]
* datoteka z zgodovino [če je mišljeno to, da učitelj lahko vidi vse študentove oddaje določena anloge - DA]
* datoteke za preverjanje na MOSSu  [ne vem zakaj gre]
* datoteke za masovno ocenjevanje (ni besedil nalog, samo vse rešitve, v komentarjih pa javljene napake)  [ne vem zakaj gre]
* kopiranje nalog [DA]
* urejanje in dodajanje nalog preko lastnega uporabniškega vmesnika (ne django admina) [DA]
* pop-up prikaz rešitev [DA]
* anonimni problemi [ne vem zakaj gre]

**Comment by matijapretnar** [comment]
* prijava na predmete - prav si mislil
* datoteke za preverjanje na MOSSu - MOSS je Stanfordova storitev za preverjanje prepisovanja (https://theory.stanford.edu/~aiken/moss/). Gor naložiš datoteke, on pa ti potem analizira podobnost. Da ne bi zaznaval, da datoteke podobne zaradi enakih navodil in testov, lahko shraniš tudi datoteke, v katerih so samo rešitve.
* datoteke za masovno ocenjevanje - poglej, kaj dobiš, če daš Shrani rezultate.
* anonimni problemi - tu je bilo mišljeno to, da lahko vseeno preneseš datoteko z nalogo, tudi če nisi prijavljen. Samo s tem je bilo precej komplikacij, ker študentje niso opazili, da niso prijavljeni, potem so se pa prijavili, samo datoteka je bila še vedno anonimna, …

**Comment by lokarM** [comment]
Verjetno je res bolje, da ukinemo anonimnega uporabnika. Končno praktično vsaka storitev sedaj že zahteva registracijo. 

Kar se pa preverjanja enakosti rešitev, pa osebno na področju začetnega poučevanja programiranja v to ne verjamem. Večina rešitev, ki jih pišejo študenti, ni daljša od 20 vrstic, sledi največ trem različnim idejam in mislim, da si z MOSSom nimamo kaj dosti pomagati. Res pa je, da ga nisem preizkusil in se morda motim  ... In tudi je res, da bi mi zadeva verjetno prav prišla, ko si bom vzel čas in v Tomota prestavil nekaj nalog iz R1 /ali pa dobil asistenta, ki ga bom znal prepričati v to ;-) /, kjer je poudarek bolj na algoritmih ...

Kar se masovnega shranjevanja tiče - osebno tega ne uporabljam, ker Toma skoraj izključno uporabljam za vaje in ne za obveznosti (DN, kolokvije ...) ker sem tu malček konservativen in mislim, da moram zadeve osebno pogledati (da lahko "težim" zaradi komentarjev, stila programiranja ...)

**Comment by matijapretnar** [comment]
> Verjetno je res bolje, da ukinemo anonimnega uporabnika. Končno praktično vsaka storitev sedaj že zahteva registracijo.

Domenjeno.

> Kar se pa preverjanja enakosti rešitev, pa osebno na področju začetnega poučevanja programiranja v to ne verjamem. Večina rešitev, ki jih pišejo študenti, ni daljša od 20 vrstic, sledi največ trem različnim idejam in mislim, da si z MOSSom nimamo kaj dosti pomagati. Res pa je, da ga nisem preizkusil in se morda motim ... In tudi je res, da bi mi zadeva verjetno prav prišla, ko si bom vzel čas in v Tomota prestavil nekaj nalog iz R1 /ali pa dobil asistenta, ki ga bom znal prepričati v to ;-) /, kjer je poudarek bolj na algoritmih ...

Izkaže se, da se tam od ene 15 vrstic naprej izjemno hitro vidi, ali je naloga prepisana. Ampak itak je, kot smo ugotovili, na tej točki postranska zadeva.

> Kar se masovnega shranjevanja tiče - osebno tega ne uporabljam, ker Toma skoraj izključno uporabljam za vaje in ne za obveznosti (DN, kolokvije ...) ker sem tu malček konservativen in mislim, da moram zadeve osebno pogledati (da lahko "težim" zaradi komentarjev, stila programiranja ...)

To je ravno namen masovnega shranjevanja - da si vse datoteke z opombami preneseš na svoj računalnik in jih tam lažje seciraš naprej. Je pa res, da same zelene kljukice študentom hitreje dajo občutek, da je stvar narejena. Mogoče bi lahko dali še eno vmesno varianto med veljavno in neveljavno rešitvijo: testi so šli čez, ampak bo še nekdo pogledal, preden bo stvar narejena?

**Comment by lokarM** [comment]
Pravzaprav nimam pravega mnenja. Načeloma se mi zdi dobro, da bi maesto zelene kljukice imeli zeleno rumeno (kockasto) kljukico, ki bi pomenila, da je zadeva šla preko testov [ko smo že pri tem - ali smo sedaj odstarnili "Naloga je pravilno rešena" in napisali raje"Naloga je prestala vse predvidene teste"], bo pa še naknadno pregledana s strani ocenjevalca. 

Ampak - kolikokrat se bo to res počelo?

**Comment by matijapretnar** [comment]
Zapiram, ker so vse relevantne manjkajoče stvari sedaj zapisane že drugje.
