### ISSUE TITLE
Vzpostavitev strežnika

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#33]
Treba bo postaviti strežnik na ARNESovem oblaku. Prav tako bi bilo dobro, da trenutni Tomo za UVP ne bi tekel na dev strežniku, da ne bomo česa ponesreči povozili. Ali bi po vzpostavitvi ARNESovega strežnika UVP prestavili tja, trenutnega pa bi imeli za testiranje?

@gregorjerse?

**Comment by gregorjerse** [comment]
On Friday, April 17, 2015 06:41:57 AM Matija Pretnar wrote:
> Treba bo postaviti strežnik na ARNESovem oblaku. Prav tako bi bilo dobro, da
> trenutni Tomo za UVP ne bi tekel na dev strežniku, da ne bomo česa
> ponesreči povozili. Ali bi po vzpostavitvi ARNESovega strežnika UVP
> prestavili tja, trenutnega pa bi imeli za testiranje?
> 
> @gregorjerse?

Vsekakor. Če imaš podatke za dostop do ARNESa mi jih posreduj, pa bom jaz 
uredil osnovno namestitev novega strežnika. 

LP,
Gregor

**Comment by matijapretnar** [comment]
Bom uredil na ARNESu in te obvestim. @lokarM: ali FMF že ima kakšno virtualko na ARNESovem oblaku?

**Comment by matijapretnar** [comment]
@lokarM mi je že odgovoril v živo :)

**Comment by gregorjerse** [comment]
Virtualka je sedaj postavljena in na njej tece Tomo (v dockerju). Ni pa se SAML prijave. Bo to potem urejal Nino?

**Comment by matijapretnar** [comment]
Za strežnik bi potrebovali še domensko ime. Kakšne ideje? Ali lahko tomo.fmf.uni-lj.si kaže kar tja?

**Comment by lokarM** [comment]
Hm, dobro bi bilo, da (vsaj meni samemu ni čisto jasno), kaj naj bi imeli na strežniku. Ubadam se s tem:

* okolje (open source koda), iz katere si lahko vsak postavi "svojega toma"
* javno dostopni sistem tomo, kjer si "vsak" (verjetno je potrebna določena selekcija -. npr. študent FMF ali dijak Gimnazije Z naj te pravice ne bi imel) načeloma lahko odpre svoj predmet in kjer vsak (hm, tudi tu bi učitelju rad dal možnost, da potrdi, ali sprejme študente ali ne) lahko  rešuje naloge
* strežnik, ki vsebuje še to + določen sistem FAQ + novice + članke + ....
* angleška različica zadeve (za kakšno mednarodno sodelovanje)
* ....

In zdi se mi da je tomo.fmf.uni-lj.si pač "lokalno" povezan s tem, kar smo se šli do sedaj (in bi morda rajši tomo.fmf.uni-lj.si obdržal ta pomen - če bomo recimo videli, da se moramo za interno uporabo "odklopiti" od zadeve na ARNESu - načeloma da ime obdržimo za lokalno FMFjevo virtualko v ARNESovem oblaku!)

**Comment by gregorjerse** [comment]
Za začetek bi jaz tja postavil samo novega tomota in bi se kasneje ukvarjal z načrtom spletne strani, ko bo ostalo delovalo kot se šika. 

Tehničnih omejitev  za to, da tomo.fmf.uni-lj.si pokaže na novi strežnik seveda ni. Moj predlog bi bil sicer bolj v smeri Lokarjevega: da damo storitvi ime, ki ni nujno vezano na FMF. Recimo tomo.uni-lj.si, ali pa www.tomo.sexy (ja, ta je še prosta :D), projekt-tomo.* ... 

@matijapretnar : ali je v pogodbi z državo morda zahtevano, da mora storitev teči na kakšnem posebnem naslovu?

**Comment by matijapretnar** [comment]
Zahtev za naslov ni, se mi pa zdi, da bo www.projekttomo.eu najbolj primeren glede na vir financiranja. Kaj pravite?

**Comment by lokarM** [comment]
Jaz bi zadevo morda  postavil na www.projekttomo.si, www.projekttomo.eu pa bi si prihranil za morebitno angleško različico.

**Comment by matijapretnar** [comment]
Ja, to je slišati smiselno. @gregorjerse & @sonjajerse: se strinjata?

**Comment by matijapretnar** [comment]
Poskusil bom dobiti tomo.si – v lasti jo ima Tomo Jeseničnik, samo kot gledam, je ne uporablja ne za spletno stran (zdaj je na Facebooku), ne za email (uporablja tomo@sgn.net). Načeloma ima objavljen tudi telefon, samo bom najprej poskusil prek skupne prijateljice, ki jo ima z Mojco :)

**Comment by matijapretnar** [comment]
Sem govoril s Tomom Jeseničnikom. Bil je zelo prijazen, samo pravi, da je že začel uporabljati to domeno (tiskati na pisarniški material ipd.), pa nekdo mu dela logo ob 20 letnici delovanja, tako da je mislil kmalu zaštartati stran in podobno. Skratka, imamo dve možnosti:

1. Rezerviramo si projekt-tomo.si / .eu / .net / .com / .org (kaj od tega je najbolj smiselno?)
2. Poiščemo krajše ime za projekt (glej http://paulgraham.com/name.html), npr. ProTo.si je še prosta.

Vprašanje je tudi, ali je smiselno rezervirati tudi sorodna imena? Malo me je sicer strah, da bi se kdo naselil na njih, ampak po drugi strani smo že zdaj prvi zadetek na Googlu, če napišeš Tomo.

Kaj menite?

**Comment by lokarM** [comment]
ProTo.si in projekt-tomo.si sta mi všeč in bi imel kar obe (ena naredi redirekt na drugo). Dodal bi še ProTo.org, ki bi jo porabil za angleško različico (če jo bomo kdaj naredili) in ProTo.net, ki bi bila "krovna" in bi kazala na vse "podrejene" Tomote.

Če pa ostanemo pri eni, bi glasoval za ProTo.si

**Comment by matijapretnar** [comment]
Na sestanku smo se dogovorili, da bo vse skupaj na eni sami strani www.projekt-tomo.si. Dokumentacija in povezava na GitHub bo pod ustreznim zavihkom.

**Comment by matijapretnar** [comment]
Strežnik je zdaj vzpostavljen (hvala, @gregorjerse). Nekaj stvari še ni videti čisto v redu, ampak bomo itak naložili nov dizajn.
