### ISSUE TITLE
Pošiljanje URL-ja v metodo za skripte

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#34]
Metoda, ki sestavi vsebino skripte za oddajanje in urejanje nalog, smiselno spada v `models.py`, vendar tam nima dostopa do HTTP zahteve, zato ne more dodati polnega URL-ja za strežnik. Trenutno dobi dodaten argument `url`, ki ga izpolnemo v `views.py`. Po mojem je najbolje, da se ta URL zapiše kar v `settings`. @gregorjerse & @sonjajerse mnenje?

**Comment by gregorjerse** [comment]
On Friday, April 17, 2015 06:44:07 AM Matija Pretnar wrote:
> Metoda, ki sestavi vsebino skripte za oddajanje in urejanje nalog, smiselno
> spada v `models.py`, vendar tam nima dostopa do HTTP zahteve, zato ne more
> dodati polnega URL-ja za strežnik. Trenutno dobi dodaten argument `url`, ki
> ga izpolnemo v `views.py`. Po mojem je najbolje, da se ta URL zapiše kar v
> `settings`. @gregorjerse & @sonjajerse mnenje?

Moje mnenje je enako kot takrat, ko sva se o tem pogovarjala: vpis v settings 
se mi zdi super ideja.
