### ISSUE TITLE
Testi osnovne funkcionalnosti

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#36]
Napisati bi bilo treba teste za vsaj vso funkcionalnost, do katere dostopajo študentje, da ne bomo česa ponesreči polomili. Se kdo javi?

**Comment by lokarM** [comment]
Ne razumem kaj misliš?

**Comment by matijapretnar** [comment]
To je letelo bolj na @gregorjerse in @sonjajerse, saj je treba napisati avtomatične teste, ki preverijo, ali na spletni storitvi delujejo vse stvari kot so prijava, ogled nalog, prenos datotek, oddajanje rešitev, … Zato, da vemo, da nismo ničesar pokvarili, ko smo spreminjali kodo.

**Comment by gregorjerse** [comment]
On Monday, April 20, 2015 01:21:37 AM Matija Pretnar wrote:
> To je letelo bolj na @gregorjerse in @sonjajerse, saj je treba napisati
> avtomatične teste, ki preverijo, ali na spletni storitvi delujejo vse
> stvari kot so prijava, ogled nalog, prenos datotek, oddajanje rešitev, …
> Zato, da vemo, da nismo ničesar pokvarili, ko smo spreminjali kodo.

Jaz se javim za teste. Naredil jih bom ta teden, če bo zneslo že jutri. In ne 
samo za te, ampak za vse. Namestil bom tudi programček ki nam bo povedal, 
koliko netestiranih metod še imamo ;)

-- 
LP,
Gregor

**Comment by matijapretnar** [comment]
A imaš kakšno idejo, kako bi lahko testirali tudi to, da downloadane python skripte delujejo pravilno? Načeloma jih lahko poženemo tudi prek fabrica.

**Comment by gregorjerse** [comment]
On Monday, April 20, 2015 04:24:42 AM Matija Pretnar wrote:
> A imaš kakšno idejo, kako bi lahko testirali tudi to, da downloadane python
> skripte delujejo pravilno? Načeloma jih lahko poženemo tudi prek fabrica.

PMSM prav lepo spadajo pod JUnit teste. Pripraviš bazo, narediš login, 
preneseš datoteko, pregledaš datoteko, zaženeš datoteko, preveriš kaj se je 
zgodilo. 

Vprašanje pa je, kaj vse bi si želel testirati. Verjetno da je prave oblike, 
da pravilno pošilja stvari na strežnik...

**Comment by matijapretnar** [comment]
> PMSM prav lepo spadajo pod JUnit teste
PMSM?

> Vprašanje pa je, kaj vse bi si želel testirati.
Imel bi že pripravljenih več nalog in več rešitev, da preverimo vse možne scenarije (pravilna rešitev, napačna rešitev, napačen secret, vse možne Check metode, izjeme, ...), nato pa bi prenesel datoteko z nalogo, v kateri bi že bile vpisane te rešitve (tako kot bi jo študent, ki bi nadaljeval od doma), jo zagnal in preveril, da je vse tako, kot pričakovano. Zdi se mi, da bi to moralo pokriti 95% primerov.

**Comment by gregorjerse** [comment]
Po mojem skromnem mnenju :)

**Comment by matijapretnar** [comment]
Ok, testi so trenutno precej pokrivni.
