### ISSUE TITLE
Preprečevanje goljufij

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#39]
Kako se bomo lotili preprečevanja goljufij, torej npr. dnevniki dostopov, beleženje IPjev, primerjava rešitev, …
Po eni strani bi na FMFju to koristili, ampak v splošnem pa nekako ni v duhu storitve. Ali vseeno napišemo stvari, pa naj jih uporablja, kdor jih hoče?

**Comment by lokarM** [comment]
zadevo bi trenutno zabeležil, da jo je smiselno narediti. Se pa trenutno ne bi ukvartjal s tem (razen, če to ne vpliva na samo kodo in je pač sedaj potrebno pustiti "nastavke" ...)
