### ISSUE TITLE
Nalaganje testnih podatkov

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#4]
Od kod bi nalagali testne podatke v bazo? Imamo sledeče možnosti

1. fixture – če prav razumem, je to zastarelo in ga nadomesti:
2. data migration – ta mi ni všeč, ker ne vem, kako bi dosegli, da bi se migracija pognala le lokalno, na strežniku pa ne
3. JSON dump – ker že imamo REST API, bi lahko podatke naložili tudi z enim POST requestom. Ker bi bilo to dobro tudi za razne masovne uvoze in izvoze, bi to zagotovo lahko uporabljali za podatke o nalogah. Ne vem pa, ali bi isto uporabljali tudi za podatke o rešitvah.
4. SQL dump – ta je še najbolj na ziher. Tu je prednost tudi ta, da lahko enostavno vzamemo žive podatke s strežnika. Ko sem delal na starem Tomotu so potem stvari s pravimi podatki vedno pokazale še na kakšen hrošč, ki ga zaradi premajhnosti testnih podatkov nisem videl.

Skratka, predlagam 3 v kombinaciji s 4. Ostali?

**Comment by gregorjerse** [comment]
Za testne podatke bi jaz uporabil 1. Fixture je deprecated samo za nalaganje začetnih podatkov za aplikacijo, kar je tudi prav. 

Vsekakor je dobro narediti tudi JSON export/import: če drugega ne že zaradi prenosa nalog.

Tudi jaz sem ponavadi uporabljal SQL dump. Za testiranje si lahko namesto fixturjev naredimo tudi nekaj sqlite baz in jih vržemo v samo git skladišče, na koncu pa moraš tako ali tako zagnati še vse teste na aplikaciji s "pravimi" podatki preden je program zrel za v produkcijo.

**Comment by sonjajerse** [comment]
Predlagam 4, ker se mi zdi, da se tako najbolj približamo realni situaciji (in kot si rekel, pokažejo se prej skriti hrošči).

**Comment by matijapretnar** [comment]
Bom pripravil nekaj testnih podatkov. Kakšne želje glede količine in teme nalog?

**Comment by gregorjerse** [comment]
Nikakršnih. Čimveč nalog in uporabnikov pa zagotovo ne bo škodilo :)

**Comment by matijapretnar** [comment]
@gregorjerse glede na to, da naj bi docker zdaj deloval, me zanima, kako najenostavneje naredimo to, da lokalna zadeva deluje identično tisti na Arnesovem strežniku?

**Comment by matijapretnar** [comment]
@gregorjerse - ali lahko nekam daš datoteke za Docker? Bazo mi lahko pošlješ po mailu, pa jo bom anonomiziral, minimiziral in dodal SQL dump v repozitorij, da bo lahko vsak probaval.
