### ISSUE TITLE
Počasno oddajanje rešitev

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#40]
Na vajah imam občutek, da je oddajanje nalog na strežnik počasnejše kot na starem Tomotu. Lahko da se tudi motim. Ali obstaja način, da bi izmerili, koliko časa trajajo posamezni deli pri oddaji? Nekaj takega kot Django debug toolbar, samo za REST.

**Comment by gregorjerse** [comment]
On Monday, April 20, 2015 02:12:33 AM Matija Pretnar wrote:
> Na vajah imam občutek, da je oddajanje nalog na strežnik počasnejše kot na
> starem Tomotu. Lahko da se tudi motim. Ali obstaja način, da bi izmerili,
> koliko časa trajajo posamezni deli pri oddaji? Nekaj takega kot Django
> debug toolbar, samo za REST.

Za posamezne dele ne vem...  Vsekakor pa lahko malo dopolnim kodo, tako da se 
bodo posamezne stvari izmerile in vrnile v rezultatu. Vsaj za debug bo dovolj 
dobro.

-- 
LP,
Gregor

**Comment by lokarM** [comment]
Danes sem ža dva ali trikrat opazil tole (sedaj pa sem štopal, ob 14:50)

Sestavil sem nalogo, rekel je, da je sestavljena prav, natipkal sem da in potem gledal napis "Shranjujem na strežnik" cca 20 sekund. Sem že hotel prekiniti, potem pa je javil, da je naloga shranjena ...

Ko sem delal doma, sem opazil isto, a se je odvilo hitreje (5-10 sek).

**Comment by lokarM** [comment]
In enako se mi dogaja tudi, ko se prijavim kot študent. Torej traja celo večnost (beri več kot 5 sekund) , da mi javi, da so v mojem programu napake (ker se izhod ne ujema s testom()

**Comment by matijapretnar** [comment]
Diskusijo o teh težavah nadaljujmo pri #83.
