### ISSUE TITLE
iOS mobilna aplikacija

### ISSUE THREAD

**Issue by sonjajerse** [matijapretnar/projekt-tomo#42]
Za testiranje iOS mobilne aplikacije potrebujemo Xcode (https://itunes.apple.com/us/app/xcode/id497799835?mt=12) in čim več iNaprav, ker virtualno oklje za testiranje aplikacij ne podpira vseh funkcionalnosti (če to sploh potrebujemo, ker imamo precej osnovno aplikacijo).

Potrebujemo tudi ključ za podpis aplikacije, ki ga dobimo preko Keychain Access apliakcije (navodila na http://docs.build.phonegap.com/en_US/signing_signing-ios.md.html) 
 
Za to je potreben status iOS Developer ( https://developer.apple.com/programs/ios/ ).

Vir in dodatne informacije: http://docs.phonegap.com/en/edge/guide_platforms_ios_index.md.html#iOS%20Platform%20Guide

**Comment by matijapretnar** [comment]
Bom to reševal naslednji teden, ko pride Barbara z dopusta.

**Comment by matijapretnar** [comment]
Mobilne aplikacije ne bomo objavili, ker se je izkazalo, da ne nudi nobene dodane vrednosti za končne uporabnike, saj že "responsive design" naše spletne storitve omogoča ustrezno funkcionalnost.
