### ISSUE TITLE
Logotipa MIŠZ in ESS

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#43]
Povsod je treba označiti financerja projekta, torej ministrstvo in evropske strukturne sklade. Logotipa (prilagam zraven) bi bilo najbolje dodati kar v footer v base.html.

![ess](https://cloud.githubusercontent.com/assets/1502128/7611220/4ee45a5a-f983-11e4-9e04-d88c64762f0b.png)
![mizs](https://cloud.githubusercontent.com/assets/1502128/7611221/503564ee-f983-11e4-8a79-2f9c5261f4f6.png)

**Comment by sonjajerse** [comment]
Ko utegneš, poglej, če je ok.
