### ISSUE TITLE
Seznam sistemov za preverjanje

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#44]
1. [WebCat](http://wiki.web-cat.org/WCWiki) 
2. [CloudCoder] (http://cloudcoder.org/)
3. [CodingBat] (http://codingbat.com/)
4. [TuringsCraft](http://turingscraft.com/)
5. [MyProgrammingLab] (http://www.pearsonmylabandmastering.com/northamerica/myprogramminglab/educators/features/index.html)
6. [PracticeIt!] (http://practiceit.cs.washington.edu/index.jsp)
7. [P3G] (http://wcipeg.com/problem/acmtryouts0a)
8. ... Putko, UVJudge in ostale pa poznate

Pri teh sistemih je smiselno pogledati, kako imajo rešen sistem izmenjave nalog (če je to možno), dodajanja nalog, iskanja nalog ...

**Comment by matijapretnar** [comment]
@lokarM, ali si na te sisteme že prijavljen? Ali lahko prosim narediš kratek povzetek, torej za tiste ideje, ki bi prišle v poštev, poveš, kako delujejo?

**Comment by lokarM** [comment]
* Žal je večina zadev tipičnih "projektnih". Torej - opisan imajo sistem pridobitve gesla - ampak tudi po treh mailih ne dobim odgovora.

* Bom nekaj napisal glede po moje zanimivih zadev. 

* Za nekaj sistemov sem jih nameraval namestiti na testni računalnik (oz, naj bi mi to naredil @gregorjerse), pa še nismo prišli do tega ...
