### ISSUE TITLE
Urejanje nalog na domači strani

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#50]
Tam, kjer je seznam sklopov na domači strani, manjkajo gumbi za urejanje. Ker se tako tu kot pri pregledu predmeta uporablja isti vzorec, sklepam, da ni nastavljena spremenljivka `show_teacher_forms`.

**Comment by sonjajerse** [comment]
Res je. Popravljeno.

**Comment by matijapretnar** [comment]
Super!

Closed by c79807d25390851fad1a75432f832d18ad5fc17e.
