### ISSUE TITLE
Pregled napredka učencev

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#52]
Zaenkrat lahko iz starega Tomota skopiramo tisto razpredelnico s pregledom pravilnosti, ampak bi bilo dobro stvar še enkrat premisliti, kaj vse bi radi videli.

**Comment by matijapretnar** [comment]
Ok, napisal sem:

* pregled uspešnosti reševanja pri sklopu (cirka tak, kot je bil na starem Tomotu). Dobi se ga, če na vrhu sklopa pritisneš "Show progress"
* natančen pregled uspešnosti reševanja učenca, ki ga dobiš, če v kateremkoli od prejšnjih dveh pregledov uspešnosti klikneš na ime učenca
* splošen pregled uspešnosti pri predmetu, ki ga dobiš, če na vrhu predmeta klikneš "Browse list of users".

Pri prvih dveh pogledih te bi moral klik na progress bar odpeljati na pregled učenčevih rešitev, samo to je treba še narediti do konca. Se priporočam za komentarje, predvsem @lokarM, ker sta @sonjajerse in @gregorjerse že videla in malo pokomentirala.

**Comment by sonjajerse** [comment]
Včeraj sem na git dodala popravek, da te klik na progress bar odpelje na učenčevo rešitev - v veji new_solution_view. A ne dela ok?

**Comment by lokarM** [comment]
* Klik me vrže na pregled moje uspešnosti in ne na uspešnost študenta.

* Ko kliknem na ime študenta, me vrže na podrobnejši pregled njegove uspešnosti (mislim, da je tako). Ampak nikjer ni njegovega imena, tako, da sem lahko že "pozabil".

* Saj barvno kodiranje za vsako podnalogo je čisto ok, ampak sam bi zraven rad imel še npr. podatek o tem. koliko je sploh nalog (sedaj moram "ceniti" - aha, ta je rešil prav 3 od 7, 2 je rešil narobe, 2 pa ni reševal)

* pogrešam sumarne podatke kot so pri starem Tomu (npr. to podonalogo je prav rešilo 42 študentov, 5 pa narobe).

**Comment by lokarM** [comment]
Pri https://tomo.fmf.uni-lj.si/uvp/course/1/course_users/ (torej če na vrhu predmeta klikneš "Browse list of users") klik na progress bar ne naredi nič.

**Comment by lokarM** [comment]
Mimogrede - seznam uporabnikov je urejen narobe (šumniki delajo probleme ...) - Žilavec je pred Zmazek.

**Comment by sonjajerse** [comment]
mislim, da gledaš še staro verzijo.

**Comment by lokarM** [comment]
Gledam to, kar je na https://tomo.fmf.uni-lj.si/esma/

**Comment by sonjajerse** [comment]
ja, ampak tam je še stara verzija. Nova pride, upam, kmalu

**Comment by matijapretnar** [comment]
Ne, na https://tomo.fmf.uni-lj.si/esma/ je že nova verzija, sem jo dal danes zjutraj gor.

**Comment by matijapretnar** [comment]
> Klik me vrže na pregled moje uspešnosti in ne na uspešnost študenta.
>
> Ko kliknem na ime študenta, me vrže na podrobnejši pregled njegove uspešnosti (mislim, da je tako). Ampak nikjer ni njegovega imena, tako, da sem lahko že "pozabil".

Bomo uredili.

> Pri https://tomo.fmf.uni-lj.si/uvp/course/1/course_users/ (torej če na vrhu predmeta klikneš "Browse list of users") klik na progress bar ne naredi nič.

Verjetno je najbolj smiselno, če te to tudi odpelje na pregled uspešnosti študenta?

> pogrešam sumarne podatke kot so pri starem Tomu (npr. to podonalogo je prav rešilo 42 študentov, 5 pa narobe).

A bi bilo smiselno, da učiteljem to pokažemo kar z majhnim progress barom na strani z besedilom naloge?

> Saj barvno kodiranje za vsako podnalogo je čisto ok, ampak sam bi zraven rad imel še npr. podatek o tem. koliko je sploh nalog (sedaj moram "ceniti" - aha, ta je rešil prav 3 od 7, 2 je rešil narobe, 2 pa ni reševal)

Kako bi to najbolj pregledno prikazali? Še z majhnimi številkicami zraven progress bara?

**Comment by matijapretnar** [comment]
> Ne, na https://tomo.fmf.uni-lj.si/esma/ je že nova verzija, sem jo dal danes zjutraj gor.

Zdaj šele vidim, Sonja odgovarja glede tega, da vidiš lastne rešitve. Ja, tega še nisem dal gor.
