### ISSUE TITLE
Podpora za druge jezike

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#53]
Trenutno so vse naloge narejene iz iste vzorčne datoteke: tiste za Python. Podobno bi seveda lahko naredili tudi za druge jezike, ampak bolj splošno, ne samo, da spreminjamo vzorčno datoteko, kot je bilo na starem Tomotu. Npr. pri C-ju je bolj smiselno za vsako nalogo prenesti zip z .c in .h datoteko, pa verjetno še kakšen makefile, ki se ga zažene. Podobno bi lahko bile Pythonove naloge bodisi zapletene (kot so zdaj, z dostopom do celotne knjižnice) ali enostavne (kjer bi učitelji le napisali, na katerih vrednostih se preveri delovanje funkcije).

**Comment by matijapretnar** [comment]
To zdaj dela.

**Comment by dimes123** [comment]
Plan dela:
- [ ] Napisati program v C#, ki preverja samega sebe
- [ ] Izluščiti podatke
- [ ] Prepustiti Blažu, da opravi vse, ker pač gre na potovanje sredi semestra
