### ISSUE TITLE
Prijava na predmete

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#54]
Treba je ustvariti vmesnik, v katerem se ureja prijavo v predmete, torej:

* učenci se lahko prijavijo v predmete
* učitelji pri svojih predmetih vidijo (in urejajo) učence in učitelje

**Comment by lokarM** [comment]
verjetno je smiselno, da ima

* učenci se lahko prijavijo v predmete

podobno funkcionalnost, kot Moodle, torej, da učitelj lahko (seveda ne pa nujno) predmet opremi s ključem, tako, da se ne more vsak učenec po lastni izbiri prijaviti v predmet

**Comment by matijapretnar** [comment]
Na sestanku smo se dogovorili, da bo prijava na predmet bolj lahkotna - vsak lahko vidi naloge pri predmetu, in če se odjavi, se zgodovina oddaj ne izbriše. Študent lahko samo nekatere od svojih predmetov doda med priljubljene, s čimer se mu kažejo na vhodni strani.

Učitelj pa zato, da ne bo imel prevelike gužve, med tistimi, ki imajo predmet med priljubljenimi, in med tistimi, ki so že oddali kakšno nalogo, lahko izbere skupino posameznikov, ki jim želi slediti.

**Comment by matijapretnar** [comment]
Še to: glede na to, da računamo, da bo sistem uporabljalo na tisoče učiteljev, bomo vsakemu predmetu dodali še polje za šolo, s čimer bomo olajšali iskanje po vseh možnih predmetih. Za začetek bomo predmete vnašali ročno, da bomo poskrbeli, da ne bo napačnih vnosov.

**Comment by matijapretnar** [comment]
Razbito na #65 in #66
