### ISSUE TITLE
Popularizacija

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#55]
Kot gledam, so vse stvari, ki bi jih morali narediti, bodisi narejene bodisi imajo odprt issue na Githubu. Edina (razmeroma ključna :smiley:) stvar, ki manjka, je predstavitev storitve uporabnikom. Dobršen del smo (ste) naredili že na SIRIKTu, nekaj bo na ISSEPu in VIVIDu, bi bilo pa dobro pred tem imeti že nekaj uporabnikov, da se bomo tam lahko pohvalili.

Pred tem bo treba vzpostaviti javni strežnik (issue #33, kjer moramo dobiti domeno). @lokarM, mogoče ti najbolj veš, kako naprej? Verjetno bo treba napisati navodila, nato pa uporabiti veze in poznanstva ter poslati vabila potencialnim interesentom?

**Comment by lokarM** [comment]
* Kot je na #62, se najprej pripravijo filmčki
* @sonjajerse naj bi (glede na sestanek) pripravljala dokumentacijo
* stvar je potrebno postaviti na spletni strežnik 
* na strežniku napisati način, kako učitelj pride do statusa učitelja in svojega predmeta
* na strežnik moramo postaviti en ali dva "predmeta", ki služita kot vzorec

Ko je to narejeno:
* bom poslal obvestilo (vabilo) učiteljem, ki so v zadnjih letih bili na ŠPIRI
* objavil novico na forumih za učitelje računalništva
* objavil novico na omrežju SIO
* ....
