### ISSUE TITLE
Jezik

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#57]
Načeloma mešamo jezike. Tako imamo na istih straneh

"Prenesi datoteke" in "Show progress"
"Copy" in "Izbriši"

**Comment by matijapretnar** [comment]
Načeloma bo storitev zaenkrat v slovenščini, za ISSEP delavnico pa moramo pripraviti kratek sklop nalog v angleščini.

**Comment by matijapretnar** [comment]
Stvari so načeloma prevedene, jih je pa treba še enkrat dobro pregledati.

**Comment by lokarM** [comment]
Sedaj je na prvi strani "Add to favorites" (prej je bilo slovensko - dodaj med priljubljene /a to naj bi se tako ali tako popravilo v Dodaj med moje predmete/
