### ISSUE TITLE
Check.input & Check.output

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#59]
Dodal bom še funkciji za preverjanje programov, ki niso funkcije, temveč komunicirajo preko `input` & `print`. Predlagam `Check.input(vhod)`, ki dane teste izvede ob tem, da na standardni vhod pošlje nize v seznamu `vhod`, ter `Check.output(ukaz, izhod)`, ki izvede dane ukaze (ponavadi bo to kar `Check.current_part['solution']`) in pogleda, ali izpisani nizi ustrezajo seznamu `izhod`. Pri tem je `Check.input` context manager, tako kot `Check.in_file`, da lahko Tomo sporoči:

    Pri vnešenih nizih ... je prišlo do naslednjih napak...

Uporablja se pa kot:

    with Check.input(['Matija', 'Pretnar']):
        Check.output(Check.current_part['solution'], ['Živjo, Matija Pretnar!', 'Kako si?'])

Dve vprašanji:
1) ali bomo `Check.output` uporabljali še na čem drugem kot na trenutni rešitvi? Sprašujem zato, ker je `Check.current_part['solution']` en velik niz, pri `Check.run` pa podamo seznam nizov, ki se združijo v en velik niz. Mogoče lahko naredimo tako, da pri obeh preverimo, ali je seznam ali niz, in v prvem primeru združimo vse v en niz, v drugem pa ne?

2) ali pri `Check.output` razliko med dejanskim in pričakovanim izpisom prikažemo z dvema seznamoma ali z diffom, tako kot pri `Check.out_file`?

Kaj menite, @sonjajerse @gregorjerse in @lokarM?

**Comment by lokarM** [comment]
Dobra ideja. 
Odg.1 .: po moje le na trenutni rešitvi.
Odg. 2.: Verjetno bo seznam bolj ilustrativen, oz. lažje razumljiv za študenta
