### ISSUE TITLE
Napredna dokumentacija

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#61]
Poleg osnovne dokumentacije bo treba narediti neko zbirko naprednejših testov (kot smo se pogovarjali na sestanku). @lokarM, ali lahko ti pripraviš Markdown z osnovnimi primeri?

**Comment by lokarM** [comment]
Pri zadnjih nalogah, ki jih opremljam z značkami, sem dodal še sklop značk 

check - funkcije # naloge, pri katerih testiramo uporabo prepovedanih ali zapovedanih funkcij/metod
check - dolzina # naloge, pri katerih testiramo dolžino rešitve
check - naklj # naloge, kjer za testiranje uporabljamo psevdo naključne parametre
check - datoteke # pri testih ustvarimo datoteke
check - preveriDatoteke # pri testih preverjamo ustvarjene datoteke
check - ustaviPriPrviNapaki # naloge, kjer so testi izvedeni tako, da se ustavi pri prvem napačno rešenem testu
check - oglej # testiranje, ki se ga morda splača pogledati

ki sem jih potem uporabljal pri določenih nalogah.

**Comment by lokarM** [comment]
Ali bi bilo smiselno, da delovanje Check dela časovno omejimo - če zadeva v recimo toliko in toliko časa ne vrne rešitve, se javi, da je čas pri tem in tem testu pretekel.

**Comment by lokarM** [comment]
Recimo za

```
def vsota_nterk(s, n):
    '''Računanje naj n-terke v velikih seznamih'''
    najvecja = vsota = sum(s[:n]) # začetni kandidat je vsota prvih n
    for i in range(n, len(s)):          # sestevamo ze sproti
        vsota += s[i] - s[i-n]          # vsakic ko povecamo indeks za 1, se
        if vsota > najvecja:            # prvi element odsteje, naslednji pa doda
            najvecja = vsota
            
    return najvecja
```

bi radi napisali test 
```
sez = []
for i in range(10**4):
    sez.append(1)
Check.equal("vsota_nterk("+str(sez)+",1000)", 1000)
```
in če bodo študenti zadevo reševali z dvojno  zanko (notranjo svsoto vsakič sproti ...)
