### ISSUE TITLE
Uvodna predstavitev

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#62]
Ko bo dokumentacija napisana, bi bilo dobro, da bi za tiste, ki jim ne paše toliko brati, naredili par osnovnih filmčkov:

1) kratka reklama (1-2 minuti) za to, kaj Tomo omogoča
2) uvodni filmček za študente (5-10 minut), ki gre čez ves potek reševanja
3) uvodni filmček za učitelje (10 minut), ki gre čez ves potek urejanja in pokaže, kje je dokumentacija.

Filmčke lahko naredim jaz, me pa zanima, kaj si @sonjajerse, @gregorjerse in @lokarM mislite o tem.

**Comment by lokarM** [comment]
Odlična ideja. Morda (če kdo to obvlada, jaz žal ne), bi 1 poskusili narediti zelo dinamično, res v obliki reklame. Morda z orodji, kot je https://www.powtoon.com

**Comment by matijapretnar** [comment]
Namesto uvodnega filmčka lahko naredimo tudi enostavne prosojnice, npr https://speakerdeck.com - za osnovo vzamemo tiste za poster.

**Comment by matijapretnar** [comment]
Mislil sem nekaj takega:
[predstavitev.pdf](https://github.com/matijapretnar/projekt-tomo/files/11390/predstavitev.pdf)

Se priporočam za pripombe.

**Comment by matijapretnar** [comment]
Še kako je videti v živo:
<script async class="speakerdeck-embed" data-id="6ec1b05b5f9b4dad964da31b47471a98" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>

**Comment by sonjajerse** [comment]
Mislim da lahko komentar 'Na začetni strani izberemo sklop, ki ga bomo reševali' uporabnika zavede v prepričanje, da v predmetu obstajajo samo sklopi, ki se vidijo na strani s seznamom predmetov in da drugih ni. 

Drugače se mi zdi fajn. Mogoče bi še dodali slikice, kako si ogledamo svoje rešitve in jih primerjamo z uradnimi.

**Comment by lokarM** [comment]
Odlično. Vse pohvale! Morda manjka še prva (druga) prosojnice, kjer z zvezdico opremimo predmet, kjer želimo, da učitelj spremlja naš napredek!

**Comment by matijapretnar** [comment]
Zdaj sem dal na uvodno stran.

@sonjajerse: to bi mogoče bilo ustrezno, vendar bi potem moral rešitev, ki sem jo napisal, zamenjati z eno slabšo, da bi bila primerjava smiselna, pa se mi ne da še enkrat delati screenshotov :)
@lokarM: hotel sem dodati prikaz dela za nekoga, ki storitev že uporablja (pa tudi tu se mi zdajle ne da popravljati slik :)

**Comment by lokarM** [comment]
Fino. Tomo (storitev ;-) ) je sedaj še boljši!
