### ISSUE TITLE
Pravne formalnosti

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#63]
Glede na to, da bo stvar javna, je verjetno treba urediti par pravnih traparij:

- piškotki EU
- zavedanje, da 

Predlagam, da na vstopni strani nad gumbom za prijavo piše, da se s prijavo strinjamo s pogoji poslovanja, kjer je link na pogoje poslovanja (mogoče kar modalni pogled?), v katerem zgornje piše na najbolj direkten možen način.

@gregorjerse: imaš ti kaj več izkušenj s tem? Z @lokarM in @sonjajerse smo na sestanku ugotovili, da poleg tega, da pravne službe ne bodo preveč koristne, izkušenj nimamo. Jaz se bom pozanimal še pri Alenu in Barbari Paternoster.

**Comment by gregorjerse** [comment]
On Sunday, September 06, 2015 02:24:07 AM Matija Pretnar wrote:
> @gregorjerse: imaš ti kaj več izkušenj s tem? Z @lokarM in @sonjajerse smo
> na sestanku ugotovili, da poleg tega, da pravne službe ne bodo preveč
> koristne, izkušenj nimamo. Jaz se bom pozanimal še pri Alenu in Barbari
> Paternoster.

Za piskotke je dovolj zgolj opozorilo, da se z uporabo strani strinjajo z 
njimi. Kaksni pa so pogoji poslovanja?

-- 
LP,
Gregor

**Comment by matijapretnar** [comment]
Ups, nisem dokončal stavka. Zaenkrat edini relevanten pogoj poslovanja (poleg vseh tistih trapastih, da nismo odgovorni za izgubo dobička in življenj) ta, da ima učitelj predmeta dostop do imena, priimka in vseh oddanih rešitev pri danem predmetu za vse študente, ki imajo predmet med priljubljenimi ali so pri predmetu kdaj oddali kakšno rešitev.

**Comment by matijapretnar** [comment]
Govoril sem z Barbaro, bo nekaj našla, do takrat bom pa jaz nekaj na hitro napisal.
