### ISSUE TITLE
Poster za ISSEP

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#64]
Treba bo narediti poster za ISSEP - @gregorjerse in @sonjajerse, če se prav spomnim, sta se javljala vidva?

**Comment by katjabercic** [comment]
U, poster! A lahko pomagam? ;)

**Comment by matijapretnar** [comment]
Ne, @katjabercic, ne smeš. Skoncentriraj se na svoje druge zadolžitve :)
