### ISSUE TITLE
Sledenje določenim učencem

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#65]
Kot smo se že menili v #54, bomo dodali sledeče:

> Učitelj pa zato, da ne bo imel prevelike gužve, med tistimi, ki imajo predmet med priljubljenimi, in med tistimi, ki so že oddali kakšno nalogo, lahko izbere skupino posameznikov, ki jim želi slediti.

Ker na začetku ne pričakujemo neobvladljive množice učencev, bomo prioriteto dali drugim stvarem.

**Comment by lokarM** [comment]
Hm, načeloma se s tem ne strinjam, saj bomo sistem Tomo uporabljali tudi na FMF od oktobra dalje. In vsaj jaz si zagotovo želim, da bi si lahko ogledal le uspešnost tistih, ki res hodijo k mojemu predmetu.

**Comment by matijapretnar** [comment]
Saj ne mislim, da tega ne nameravamo narediti kmalu, vendar verjetno pred zaključkom projekta ne, ker je še cel kup drugih stvari. Mogoče boš moral kak teden v oktobru še potrpeti.
