### ISSUE TITLE
Vprašalniki

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#68]
Za ISSEP in VIVID bi bilo dobro pripraviti vprašalnike (npr. na https://www.surveymonkey.com). Pomembno je, da vprašamo dve vrsti stvari:

1. stvari, ki bi nam koristile pri razvoju storitve
2. indikatorji, ki smo jih navedli v prijavi na razpis (glej RO2.4 v Obrazcu 2 v mapi Prijavna vloga).

@sonjajerse, ali lahko to pripraviš v naslednjem tednu?

**Comment by lokarM** [comment]
Predlagam, da podpiramo slovensko znanje in to naredimo na https://www.1ka.si/

**Comment by lokarM** [comment]
Za izpolnjevanje ankete lahko prosim tudi "moje" ŠPIRIjevce in tudi študente, ki so lani uporabljali Toma. 

Samo verjetno bi morala biti anketa za študente drugačna.

**Comment by sonjajerse** [comment]
Velja
