### ISSUE TITLE
Vmesnik za prijavo/odjavo na ArnesAAI

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#70]
Prijava na ArnesAAI deluje hkrati z ostalimi prijavami (Django, Google, Facebook), vendar je treba ponuditi še malo prijaznejši vmesnik. Najbolj je treba ugotoviti, kako se za tiste, ki uporabljajo AAI, ponudi drugačen logout link.

**Comment by matijapretnar** [comment]
Sem uredil. Preizkusite, če dela.

Closed by #acadad9

**Comment by lokarM** [comment]
Dela lepo. Jaz bi morda zadevo naredil še malo večjo (da še bolj "favoriziramo" to)

So pa problemi:
* prijavim se z AAI in se odjavim
* ponovna prijava za AAI - dela čisto fino
* se odjavim
* poskusim se prijaviti z Googlom - dobim Server Error 500. Naredim back na brskalniku, poskusim še enkart in zadeva dela. In to ponovim še nekajkrat: torej, če sem se prijavil z AAI, se odjavil, prva prijava z Google da Server error 500, naslednja pa uspe

Je pa še en problem - na računalniku imam več Google identitet. Tomo si zapomni, katero sem uporabljal in me ob naslednji prijavi ne sprašuje več. Ampak mislim, da je to problem z Googlom (in morda Chromom), ker nasploh ne znam Chrome prepričati, da bi zamenjal osebo. Lahko se odjavim kot oseba, ampak "noče" vprašati, da bi moral ponovno vnesti geslo, uporabnika ... 
Očitno bom moral pošteno pogledati, kako je sploh s tem kar se s kombinacijo Google/brskalniki dogaja, saj je to malo "scarry" - se odjaviš, ampak si več ali manj še vedno prijavljen :-((

**Comment by matijapretnar** [comment]
Za to napako sem odprl #79
