### ISSUE TITLE
Tooltipi na učiteljevih grafih

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#75]
Na uciteljevih grafih (tistih na vhodni strani in pri strani sklopa) bi dodal tooltipe, pri katerih se prikažejo še številčni podatki, npr. (20 veljavnih, 15 neveljavnih, 13 neoddanih) in kaj podobnega. @lokarM še kakšne ideje, kaj točno bi kje pisalo?

**Comment by lokarM** [comment]
Hm, kaže da so še določeni problemi. Pri predmetu Programiranje 1 sem z Matija.Lokar@fmf.uni-lj.si preko AAI prijavljen kot učitelj. Tam sem z Matija.Lokar@gmail.com prijavljen tudi preko googla kot učenec. To se v seznamu vidi. 

![image](https://cloud.githubusercontent.com/assets/11019265/10415981/37be16f4-7002-11e5-909a-285207ed8bb6.png)

Ampak če se potem prijavim kot učitelj, ta učenec nima rešene nobene naloge:

![image](https://cloud.githubusercontent.com/assets/11019265/10415984/63ea0cc4-7002-11e5-8377-f09059272933.png)

![image](https://cloud.githubusercontent.com/assets/11019265/10415985/78dbfc96-7002-11e5-9da7-3e8079c8aa79.png)

**Comment by matijapretnar** [comment]
Prišlo je do zmede zaradi večih Google Accountov. Na Tomotu so trenutno štirje Matije Lokarji:

1. na Googlu z e-mailom matija.lokar@fmf.uni-lj.si
2. na FaceBooku brez e-maila
3.  na Googlu z e-mailom @gmail.com
4. na ArnesAAI-ju.

Oddajo ima tretji, v predmet pa je kot študent prijavljen prvi. Oddaje tretjega kot učitelj ne vidiš, ker ni prijavljen v predmet (nastavil sem, da vidiš le oddaje prijavljenih, ne vseh oddaj - načeloma bo to ista množica)

**Comment by lokarM** [comment]
Ok. Ali mi potem lahko pustis le tistega z aai in narefis enega studentskega za direktno prijavo  studentLokar, da bom lahko studentom v ponedeljek pokazal, kako se vidijo njihove oddaje in kako student vidi stvari.


Lep pozdrav Matija Lokar

<div>-------- Izvirno sporočilo --------</div><div>Od: Matija Pretnar <notifications@github.com> </div><div>Datum:11. 10. 2015  11:34  (GMT+01:00) </div><div>Za: matijapretnar/projekt-tomo <projekt-tomo@noreply.github.com> </div><div>Kp: lokarM <Matija.Lokar@gmail.com> </div><div>Zadeva: Re: [projekt-tomo] Tooltipi na učiteljevih grafih (#75) </div><div>
</div>Prišlo je do zmede zaradi večih Google Accountov. Na Tomotu so trenutno štirje Matije Lokarji:

na Googlu z e-mailom matija.lokar@fmf.uni-lj.si
na FaceBooku brez e-maila
na Googlu z e-mailom @gmail.com
na ArnesAAI-ju.
Oddajo ima tretji, v predmet pa je kot študent prijavljen prvi. Oddaje tretjega kot učitelj ne vidiš, ker ni prijavljen v predmet (nastavil sem, da vidiš le oddaje prijavljenih, ne vseh oddaj - načeloma bo to ista množica)

**Comment by matijapretnar** [comment]
Kaj pa, če uporabiš Facebook, ker tam ni zmede? Ročno prijavo bi najraje ukinil.

**Comment by lokarM** [comment]
Ja, se strinjam. Sem/bom naredil tako. 

Ali prosim lahko sedaj pobrišeš vse moje račune razen AAI in tistega s FaceBook (tu sem namenoma spremenil priimek v Loka)

**Comment by matijapretnar** [comment]
Urejeno.

**Comment by lokarM** [comment]
Sedaj z nekaj več kilometrine uporabljanja. Res bi zelo potreboval možnost da 

* za posameznega študenta vidim številske podatke koliko nalog v določenem sklopu je rešil/reševal/se ni dotaknil. 
* za vse študente skupaj videti te podatke na nivoju sklopa

Prav tako pa bi znotraj sklopa bilo dobro imeti številske podatke za posamezno nalogo in to sumarno in na nivoju študenta. 

Skratka, čim enostavneje bi rad videl:

* koliko nalog v posameznem sklopu so rešili/reševali/pustili pri miru vsi študenti 
* za posameznega študenta znotraj posameznega sklopa  koliko podnalog pri posamezni nalogi je rešil/reševal/pustil pri miru
* za posameznega študenta videl koliko podnalog (skupno, preko vseh nalog) pri posameznem sklopu je rešil/reševal/pustil pri miru

**Comment by matijapretnar** [comment]
Nekaj sem načaral. Zaenkrat bi vse pustil na tooltipih, da ne bo vmesnik preveč nagužvan. Enih stvari ne znam smiselno narediti, tako da bi bilo prej treba ugotoviti, kaj hočemo videti.

> za posameznega študenta vidim številske podatke koliko nalog v določenem sklopu je rešil/reševal/se ni dotaknil.

Kaj pomeni, da je naloga rešena? Da so rešene vse podnaloge? Tu bi se bilo najprej treba odločiti, kaj bomo kazali.

> za vse študente skupaj videti te podatke na nivoju sklopa

> koliko nalog v posameznem sklopu so rešili/reševali/pustili pri miru vsi študenti

Pri več študentih in več nalogah ne vem - ali so bolj smiselni odstotki ali števila oddaj (torej bo vsota vseh treh enaka št. študentov x št. podnalog)

![screen shot 2015-11-26 at 21 17 30](https://cloud.githubusercontent.com/assets/1502128/11430292/a10e7490-9484-11e5-8484-854647833810.png)

Na nivoju naloge te težave ni:

![screen shot 2015-11-26 at 21 17 36](https://cloud.githubusercontent.com/assets/1502128/11430295/a2460a76-9484-11e5-922b-e747e933da07.png)

> za posameznega študenta znotraj posameznega sklopa koliko podnalog pri posamezni nalogi je rešil/reševal/pustil pri miru

To lahko vidiš pri statistiki sklopa

![screen shot 2015-11-26 at 21 21 12](https://cloud.githubusercontent.com/assets/1502128/11430296/a24a1aee-9484-11e5-8e3c-3dc9fcc82eaa.png)

in pri statistiki študenta

![screen shot 2015-11-26 at 21 27 03](https://cloud.githubusercontent.com/assets/1502128/11430297/a2a98574-9484-11e5-90ce-c0467b6c7a3a.png)

> za posameznega študenta videl koliko podnalog (skupno, preko vseh nalog) pri posameznem sklopu je rešil/reševal/pustil pri miru

A tako?

![screen shot 2015-11-26 at 21 27 09](https://cloud.githubusercontent.com/assets/1502128/11430294/a23d0dfe-9484-11e5-8676-0d35de3199eb.png)

**Comment by lokarM** [comment]
Odlično! Pri prvi sliki mislim, da je smisleno, da je zadeva v %. Saj te na nivoju celotne "mase" študentov verjetno bolj zanimajo odstotki kot abs. številke. 

Zelo dobra odločitev, da te številke "obesiš" na tooltipe. S tem je design res bistveno bolj čist!

**Comment by matijapretnar** [comment]
Ok, zaenkrat sem tretuntno varianto dal gor, pa poskusi in povej, kaj se in kaj se ne obnese.
