### ISSUE TITLE
Zaprtje starih Tomotov

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#78]
Trenutno imamo nebroj strežnikov. Za polovico, kot npr tomo1314 jih sploh ne veste :) Predlagam, da imamo le dva strežnika - www.projekt-tomo.si in testni strežnik, ki ga lahko kadarkoli pobrišemo ali zafuramo in ki je lahko na bilo katerem naslovu, npr. tyrion.fmf.uni-lj.si/tomo/. Domena tomo.fmf.uni-lj.si naj preusmerja na www.projekt-tomo.si.

Vprašanje je, kaj storimo s starimi Tomoti. Težavi sta dve:

1) prenos oddanih rešitev - prvič so nekatere oddaje še v starem formatu (s preambulo, drugače implementirano zgodovino, ...) in bo prenos zahteval preveč dela. Na Tomotu, ki smo ga letos uporabljali pri UVP, te težave ni, je pa ta, da so uporabniki vezani na student.fmf LDAP, zato ne vem, kako bi jih uporabljal.

Predlagam, da prastare Tomote zapremo, nekam shranimo SQL dump, če bi slučajno kdo karkoli hotel (zaenkrat sem to naredil že parkrat, pa ni bilo treba - študente oddaje najverjetneje zanimajo le do točke, ko opravijo predmet). Potem tomo.fmf.uni-lj.si za tiste predmete, ki so ga letos že začeli uporabljati (npr. Nino pri fizikih) za letos še pustimo, naslednje leto pa ga preusmerimo. Nato pa vse nove predmete izvajamo na www.projekt-tomo.si. Če se da, poskusimo tudi trenutne predmete prenesti na novega Tomota.

2) prenos starih nalog - naloge iz Pythona je @lokarM že večinoma prenesel, ostanejo pa še naloge iz R-ja, za katere je treba najprej vklopiti podporo za R. Bom govoril z Janošem in Alenom, če je za to še interes ali sta preklopila bolj na projektni način dela.

**Comment by jaanos** [comment]
Vidim, da me omenjaš, pa lahko kar tukaj odgovorim. Tomota še uporabljamo, in se mi zdi zelo koristen predvsem na začetku semestra, da lahko spremljam, kako gre študentom, kakšne napake delajo, itd. Kasneje gremo sicer res na projekte, tako da ga za kakšne domače naloge ali izpite nismo uporabljali, od kar sem asistent pri Programiranju 1/APPR.

Danes smo tako začeli delati na tomo.fmf.uni-lj.si, seveda pa ne bi imel nič proti, če gremo že letos na nov sistem. Seveda pa to ne bi bilo ravno smiselno, če bi nam ostale npr. samo še ene vaje na Tomotu.

**Comment by matijapretnar** [comment]
@jaanos, hvala za informacije. Ker nova verzija Tomota zaenkrat podpira le Python, bi bilo preveč dela (in napak), če bi poskušali podpreti R že sedaj. Tako bo trenutni tomo.fmf.uni-lj.si delal do konca tega šolskega leta, podporo za R in prenos nalog pa obljubim do začetka naslednjega leta.

**Comment by nbasic** [comment]
Jaz pri fizikih še vedno uporabljam starega Tomota. Bom med poletjem (ko bom, upam, imel čas) migriral vse naloge na novega Tomota, do takrat pa upam, da bo stari ostal :smiley:

**Comment by matijapretnar** [comment]
Stvar je dogovorjena. Stari tomo.fmf.uni-lj.si bo delal do konca leta. Glede na to, da podpora za več jezikov že obstaja, prehod na R ne bo več posebna težava.

**Comment by andrejbauer** [comment]
Za oddane rešitve me niti ne zanima, kako pa se prenese naloge? Gre za predmet Računalništvo za fizike, o katerem je govoril @rbasic.

**Comment by matijapretnar** [comment]
Zaenkrat še ne dela podpora za R, pa tudi za preambule ne vemo, kako bi jih rešili, tako da zapiranje odlagam za nedoločen čas.

**Comment by matijapretnar** [comment]
Ok, čisto vse naloge s starega strežnika sem sedaj prenesel na novega. @jaanos, kot gledam, imate APPR šele v naslednjem semestru. Z @andrejbauer sva danes ugotovila, kaj storiti s preambulami, pa tudi precej podpore za R mi že dela, tako da s prehodom ne bi smelo biti nobenih težav. Ali potem stari strežnik lahko izklopim? @lokarm in @nbasic, ali ga vidva slučajno še uporabljata?

**Comment by jaanos** [comment]
Tako je, APPR je letos v drugem semestru. Starega strežnika tako trenutno ne uporabljam - če bo novi pripravljen za R do začetka drugega semestra, se lahko stari zaradi mene ugasne.

**Comment by lokarM** [comment]
Kar se mene tiče, se stari Tomo lahko upokoji ...

**Comment by andrejbauer** [comment]
Starega Tomota ne zapiraj. Novemu Tomotu manjka kar precej funkcionalnosti, ki jo ima stari Tomo.

**Comment by matijapretnar** [comment]
@andrejbauer, @jaanos, @aosojnik, še kakšne potrebe po starem Tomotu?

**Comment by aosojnik** [comment]
Jaz sem s starega Tomota pobral vse kar sem rabil.

**Comment by jaanos** [comment]
Z moje strani ne - naloge so prenesene na novega in ga že veselo uporabljamo.

**Comment by matijapretnar** [comment]
Zaprto. Stran zdaj preusmeri na www.projekt-tomo.si.
