### ISSUE TITLE
POST za urejanje problemov

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#8]
Potrebovali bi tudi nekaj, na kar učitelj pošlje podatke za urejanje problema. V stari verziji se pošlje:

- id problema (že obstoječ - nove probleme narediš preko spletnega vmesnika)
- naslov problema
- opis problema
- preambula (tega zdaj ni več)
- za vsak del problema pa še:
    - id, če že obstaja. Če ne, se za id nastavi 0 in se tak del naredi na novo
    - opis dela
    - rešitev dela
    - testi dela
    - uraden `secret`

Prek tega vmesnika lahko dodajaš nove dele, brisati jih pa ne moreš. Nekaj v tem stilu bi rabili tudi sedaj, da bodo učitelji lahko dodajali naloge.

**Comment by gregorjerse** [comment]
Django REST podpira nested serializacijo. Torej znotraj objekta Problem lahko podaš tudi Parte, ki spadajo zraven. Predlagam, da uporabimo kar to. Primer takšnega JSONa.

```json
[
    {
        "id": 1, 
        "parts": [
            {
                "id": 1, 
                "description": "Del 1", 
                "solution": "pass", 
                "validation": "pass", 
                "secret": "[2,3,4]", 
                "_order": 0, 
                "problem": 1
            }, 
            {
                "id": 2, 
                "description": "Del 2", 
                "solution": "pass", 
                "validation": "pass", 
                "secret": "[\"a\", \"bah\"]", 
                "_order": 1, 
                "problem": 1
            }
        ], 
        "title": "Prvi problem", 
        "description": "Opis prvega problema"
    }
]
```

Logiko kaj se zgodi s temi Parti (vedno novi, se stari lahko spremeni...) moramo implementirati sami.

**Comment by matijapretnar** [comment]
* Ja, edino polje `_order` bi črtal iz JSONa. Prvi je itak interni Djangotov, zato se začne z `_`. Prebere naj se ga kar iz vrstnega reda partov v seznamu.

* Načeloma lahko tudi polje `problem` črtamo, da bomo imeli normalizirano.

* `secret` je še vedno v stari obliki, pa pri prvem primeru je napačen, ker ni seznam nizov.

**Comment by gregorjerse** [comment]
Jaz problema ven ne bi metal. Če bomo kdaj serializacijo Parta potrebovali samo zase, nam bo prišel še kako prav.

**Comment by matijapretnar** [comment]
No, serializacije Parta ne bomo potrebovali, pa tudi če jo bomo, je ne bo tak problem dodati. Kako sicer kaže s tem? Tudi če ni najbolj elegantna rešitev, jo je treba čimprej usposobiti.

**Comment by matijapretnar** [comment]
Zdaj moram jaz skripto napisati.

**Comment by matijapretnar** [comment]
Če spremeniš vrstni red partov v datoteki, se to ne odraža na strežniku. Kot gledam, bo treba kodo napisati na novo, saj gremo zdaj po skupinah (novi deli, posodobljeni deli, izbrisani deli, ...), bo pa treba pri novih in posodobljenih iti po takem vrstnem redu, kot so bili uploadani, da bomo v pravem vrstnem redu nabrali id-je.
