### ISSUE TITLE
Testiranje vhoda/izhoda

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#80]
Tole 

     with Check.input(['Matija', '10', '15', '115']):
         Check.output(Check.current_part['solution'], [....]

je res priročno. Opazil pa sem, da zaključnih presledkov ne upošteva (torej, če ima otput na koncu več presledkov kot je predvideno. 

Je načeloma odprto vprašanje, ali naj bo primerjanje strogo, ali pa je to vseeno.

**Comment by lokarM** [comment]
@matijapretnar mi je napisal v [https://www.projekt-tomo.si/problem_set/22/](https://www.projekt-tomo.si/problem_set/22/)  test oblike

```python 
with Check.input(['14', '35']):
    Check.output(Check.current_part['solution'], [
        'Ur: 14',
        'Minut: 35',
        'Kot med urnim in minutnim kazalcem je 132 stopinj in 30 minut.',
])
```
in me je kar malček "sram", da ga nisem scopral sam. AMpak da malo prispevam ...Morda bi ga raje napisali kar kot

```python 
vh = ['14', '35']
izh = ['132', '30']
with Check.input(vh):
    Check.output(Check.current_part['solution'], [
        'Ur: ' + vh[0],
        'Minut: ' + vh[1],
        'Kot med urnim in minutnim kazalcem je ' + izh[0] + ' stopinj in ' + izh[1] + ' minut.',
])
```

Kolikor sem videl, gre ;-)
In to je potem še lažje popravljati in delati kopije .... 

In mislim, da je to en tipičen primer, ki spada v dokumentacijo za učitelje @sonjajerse

**Comment by lokarM** [comment]
Npr. kopija za nov test zahteva popravek le `vh` in `izh`. 

```python
vh = ['12', '0']
izh = ['0', '0']
with Check.input(vh):
    Check.output(Check.current_part['solution'], [
        'Ur: ' + vh[0],
        'Minut: ' + vh[1],
        'Kot med urnim in minutnim kazalcem je ' + izh[0] + ' stopinj in ' + izh[1] + ' minut.',
])
```

Seveda bi lahko potem stvar spravili še v zanko preko "baterije" testnih primerov, a ...

**Comment by matijapretnar** [comment]
Ja, tole z `vh[x]` in `izh[x]` mi je videti v redu.
