### ISSUE TITLE
Prva stran

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#82]
V določenih kombinacijah OS/brskalnik je na vrhu prve strani bel rob  (črn okvir sem dodal, da se vidi belina ;-) )

![image](https://cloud.githubusercontent.com/assets/11019265/10480102/a50c8390-7268-11e5-877f-7d59cc0e1323.png)

**Comment by lokarM** [comment]
Ni na prvi strani, ampak Tomo mi je nenadoma zadevo izpisal takole

![image](https://cloud.githubusercontent.com/assets/11019265/10520249/8df479e0-7369-11e5-9ee9-c030d943d32f.png)

in čez nekaj časa še

![image](https://cloud.githubusercontent.com/assets/11019265/10520285/bbdfe04c-7369-11e5-9a02-477947c26ebd.png)


Pri obeh stvareh je sicer pomagal Refresh, ampak ne vem, kaj točno se dogaja ...

**Comment by matijapretnar** [comment]
Pri prvi je videti, da css ni bil v redu naložen, pri drugem pa, da se je pokvaril MathJax.

**Comment by lokarM** [comment]
Ja predvidevam. ZAdevo sem javil več ali manj le za to, ker nisme bil čisto prepričan, ali je težava v "response time" strežnika ali na moji strani. Zadevo zaenkrat zapiram, saj je bila verjetno težava pri meni ...

**Comment by matijapretnar** [comment]
Ampak beli robovi so pa še vedno, kajne?

**Comment by lokarM** [comment]
Ja, res je ... In ta beli rob je občasno - včasih ga ni!!! Ne znam natanko opisati, kdaj je in kdaj ne.

**Comment by lokarM** [comment]
Še kar se "dna" tiče. Ali lahko

*Operacijo delno financira Evropska unija iz Evropskega sklada za regionalni razvoj ter Ministrstvo za izobraževanje, znanost in šport. Operacija se izvaja v okviru Operativnega programa krepitve regionalnih razvojnih potencialov v obdobju 2007—2013, razvojne prioritete: gospodarska razvojna infrastruktura; prednostne usmeritve: informacijska družba*

spremenimo v

*Operacijo postavitve sistema je delno financirala Evropska unija iz Evropskega sklada za regionalni razvoj ter Ministrstvo za izobraževanje, znanost in šport. Operacija se je izvajala v okviru Operativnega programa krepitve regionalnih razvojnih potencialov v obdobju 2007—2013, razvojne prioritete: gospodarska razvojna infrastruktura; prednostne usmeritve: informacijska družba*

in morda dodamo še ... 

*Sama vsebina (naloge) in nadaljnji razvoj pa so plod predvsem prizadevanja številnih predavateljev in asistentov s FMF.*

**Comment by nbasic** [comment]
Uporabljam Firefox 42.0 na Ubuntu 14.04.3 LTS in redno gledam beli rob. Ker gre za "kozmetično nerodnost" se zaradi tega ne sekiram preveč.

**Comment by nbasic** [comment]
Poskusil sem še z brskalnikom Chromium, Version 45.0.2454.101 Ubuntu 14.04 (64-bit) in tudi gledam beli rob.
