### ISSUE TITLE
Podpora za IPv6

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#83]
v 3.10. Tomo na predavateljskem računalniku noče delati. Obvisi pri "Shranjujem na strežnik" /ni dovolj počakati 20 sekund/ Ni odvisno od tega, kako se prijaviš na računalnik.

Na srečo pri študentih dela ...

Ne vem, kako je v 3.11

**Comment by lokarM** [comment]
Morda v 3.10 stvar dela, le premalo časa sem čakal. Ampak dejansko gre za problem, ker na predavateljskem računalniku (ki je v 3.10, 3.11 in 3.12) na omrežju FMF "buljiš" v napis "Shranjujem na strežnik" pol minute, preden se kaj zgodi!

**Comment by gregorjerse** [comment]
On Friday 16 of October 2015 04:48:32 lokarM wrote:
> Morda v 3.10 stvar dela, le premalo časa sem čakal. Ampak dejansko gre za
> problem, ker na predavateljskem računalniku (ki je v 3.10, 3.11 in 3.12) na
> omrežju FMF "buljiš" v napis "Shranjujem na strežnik" pol minute, preden se
> kaj zgodi!

Ali je problem samo v 3.10 ali še kje drugje? To je namreč lahko povezano tudi 
s počasnostjo našega Tomota, kar pa moram odpraviti jaz.

-- 
LP,
Gregor

**Comment by lokarM** [comment]
Kaže, da so težave prvenstveno na računalnikih v omrežju FMF. Včeraj zvečer sem od doma delal normalno, v tem trenutku na računalniku v kabinetu pa je potrebnih 30 sekund med "Shranjujem na strežnik ..." in odzivom.  In to neodvisno ali delam kot študent (reševanje nalog) ali kot učitelj (priprava nalog)

@gregorjerse Fino bi bilo, če bi se dalo ugotoviti kje in zakaj se zatakne. Sumim, da so kakšne "varnostne" nastavitve omrežja, ki povzročijo ta zamik ...

**Comment by gregorjerse** [comment]
On Wednesday 21 of October 2015 22:38:02 lokarM wrote:
> @gregorjerse Fino bi bilo, če bi se dalo ugotoviti kje in zakaj se zatakne.
> Sumim, da so kakšne "varnostne" nastavitve omrežja, ki povzročijo ta zamik
> ...

Bom prisel na FMF jutri in poskusil ugotoviti zakaj gre.

-- 
LP,
Gregor

**Comment by nbasic** [comment]
Imam vaje v 3.11 in danes sem se spet dodobra nagledal napisa `Shranjujem na strežnik ...`. Študentje seveda niso imeli teh težav.

**Comment by gregorjerse** [comment]
On Wednesday, December 09, 2015 12:32:44 PM Nino wrote:
> Imam vaje v 3.11 in danes sem se spet dodobra nagledal napisa `Shranjujem na
> strežnik ...`. Študentje seveda niso imeli teh težav.

Jutri bom spet na FMF in grem v RC, morda kaj pametnega ugotovimo.

-- 
LP,
Gregor

**Comment by matijapretnar** [comment]
Kot opažam, mi tudi SSH na www.projekt-tomo.si deluje tako počasi, da včasih obupa, preden se poveže. Ko se, pa dela normalno. Se bom v torek oglasil pri Radotu.

**Comment by matijapretnar** [comment]
Danes smo ugotovili, da ima strežnik IPv6 DNS vnos, vendar na tem IP-ju nima odprtih vrat, zato pride do timeouta, preden preklopi na IPv4. Zelo verjetno je vzrok v tem. Bom poskusil urediti.

**Comment by matijapretnar** [comment]
Malo sem gledal, vendar se nič ne znajdem. @gregorjerse in @nbasic, ali lahko vidva mogoče pomagata? Težava se vidi, če gremo na http://www.ipv6scanner.com/cgi-bin/main.py. Ko smo že pri tem, me zanima tudi, zakaj vrata 139 in 445 niso zaprta.

**Comment by matijapretnar** [comment]
Sva z Radom včeraj uspešno rešila zadevo.
