### ISSUE TITLE
Seznam študentov, ki jih upravlja učitelj

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#84]
Ves čas se "bojim" kaj se bo zgodilo z mojim predmetom. če bom zagledal tam kar neke x/y tipe (torejk osebe, ki niso "Pravi" študenti 1. letnika PM FMF. Zagotovo bi rad, da bi lahko imel "priljubljene" študente in "ostale" in da bi npr. spiske, statistike lahko gledal ločeno (vsi, prilubljeni, ostali) [večino časa me zanimajo le priljubljeni - torej tisti

**Comment by matijapretnar** [comment]
To je kopija #65.
