### ISSUE TITLE
Anketiranje

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#85]
1 - Naredim predmet Tečaj za anketo in van zložim nekaj nalog (kakih 5 sklopov ...). Vanj povabim vse ŠPIRIjevce (kot učence) in jih potem anketiram - kaj menijo o Tomo s stališča učenca. Pripraviti je torej potrebno anketo.

2 - Ustrezno anketo (ločeno) pripraviti in jo zastaviti prvčkom, ki se prvič spoznavajo (in to že zelooo kmalu, po dveh treh uporabah Toma) - torej zaggotovo do konca meseca. Prositi še NIna, da jo izvede na svojih ... [je še kdo štartal?]

 3 - ŠPIRIjevce po nekaj časa uporabe (1) "nadgraditi" v učitelje in jih prosti, naj izpolnijo še eno anketo, tokrat kot učitelji! Seveda potrebujemo "učiteljsko anketo"

4 - Pripraviti anketo za študente, ki so že prej uporabljali starega Toma in jih povabiti, da si ogledajo novega in jih anketirati.

5 - Spremljati, kaj se dogaja pri drugih predmetih (izven FMF - npr. Gimnazija Vič ...) in potem ob primernem času
   a - anketirati učence
   b - anketirati predavatelje

Seveda bi potreboval pomoč za pripravo ankete in vsega tega

**Comment by sonjajerse** [comment]
Jaz ti ankete lahko vnesem.

**Comment by lokarM** [comment]
Fino. Predlagam, da morda na 1ki kar narediš osnutek, saj je načeloma lažje delati, če je že nekaj pripravljeno. Jaz bi začel z anketo za "začetničke študente", ki se s Tomom srečujejo prvič.

**Comment by sonjajerse** [comment]
Velja. Verjetno bom začela jutri - danes je karierni sejem.

**Comment by lokarM** [comment]
Anketa za študente je sedaj "pripravljena". Namenjena je tistim, ki uporabljajo novi sistem. Prosim, če jo čimprej pogledate in sporočite pripombe. Namreč "svojimi" študentom (1. letnik PM - pričakujem cca. 30 odgovorov) bi jo rad dal v naslednjem tednu.

 @sonjajerse - če gre za kakšne oblikovne ali tipkarske napake, kar popravi "v živo". @matijapretnar - lepo prosim za mnenje ... Seveda pa bi bilo lepo, če bi kakšno rekli še @gregorjerse, @katjabercic, Nino Bašić in še kdo ...

**Comment by matijapretnar** [comment]
Ja, meni se zdi super.

**Comment by lokarM** [comment]
Pripravil sem še anketo, za katero izpolnjevanje sem prosil učitelje programa ŠPIRI (letošnje in lanske generacije), ki je dejansko kopija zgornje (torej bodo odgovori primerljivi).  Ampak načeloma sem jo želel imeti ločeno, saj osnovne izkušnje z uporabo Toma imajo. 
--------------------------
Poslano jim je bilo sledeče:

Na Fakulteti za matematiko in fiziko smo pred kratkim zaključili prenovo sistema, ki ga uporabljamo pri poučevanju Pythona. Gre za spletno storitev, dostopno na naslovu

https://www.projekt-tomo.si/

Gre za prenovljeno storitev https://tomo.fmf.uni-lj.si/, ki ste jo uporabljali pri predmetih Osnove programiranja in Programski jeziki (a je bila dostopna le za študente FMF). Sistem je sedaj pripravljen tako, da ga načeloma za poučevanje kot tudi za samo učenje lahko uporablja kdorkoli.Način dela s stališča učenca je v bistvu enak kot prej, precej pa je spremenjen uporabniški vmesnik. 

Ker novega sistema ne poznate, vas vabimo, da se najprej prijavite ter nekaj časa uporabljate sistem. Priporočam uporabo nalog v predmetu "Vzorčni predmet" (kliknite na zvezdico ob imenu, da bo uvrščen med vaše "priljubljene"). 

 
In sedaj glavna prošnja: 

Razvijalci spletne storitve Projekt Tomo (https://www.projekt-tomo.si/) želimo izvedeti vaše mnenje in predloge v zvezi s storitvijo. Zato vas prosimo, da najkasneje do 10. 11. izpolnite anketo na naslovu

https://www.1ka.si/a/74800

Potem bomo sistem lažje prilagodili vašim željam in potrebam.  Vaši odgovori so anonimni. Sistem ocenjujete kot "študenti", torej nekdo, ki se uči jezik Python s pomočjo tega sistema.

**Comment by matijapretnar** [comment]
Super, hvala!
