### ISSUE TITLE
Izvoz podatkov o pravilnosti

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#88]
Kot učitelj bi rad imel poleg "tortnih" diagramov še številske podatke. Npr. hočem hitro in na nivoju poglavja videti, da je Janez Slovenski rešil 7 nalog od 9-ih (ker je pač pogoj, da ima opravljene vaje vsaj 6 nalog od 9). In dobro bi bilo (a ni tako nujno), da bi se dalo te številske podatke izvoziti v obliki Excela ali csv

**Comment by matijapretnar** [comment]
Urejeno v #75.
