### ISSUE TITLE
AttemptSerializer za feedback

### ISSUE THREAD

**Issue by matijapretnar** [matijapretnar/projekt-tomo#9]
Polje `feedback` v modelu `Attempt` je seznam nizov. Ali se da `AttemptSerializer` popraviti tako, da bo sprejel seznam nizov v JSONu in ne niza, ki predstavlja seznam nizov v JSONU?

Poslati torej hočem `{"feedback": ["bla", "bla", "bla"], ...}` in ne `{"feedback": "[\"bla\", \"bla\", \"bla\"]", ...}`.

**Comment by gregorjerse** [comment]
Popravljeno v mojem novem pull requestu.

**Comment by matijapretnar** [comment]
Super, postopaš enako kot za #10.
