### ISSUE TITLE
Prikaz uspešnoti študentov in neobjavljene naloge

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#92]
Pri pregledu uspešnosti študentov nima smisla, da so prikazane naloge, ki jih študenti ne morejo reševati (ker so še skrite). Npr. 

![image](https://cloud.githubusercontent.com/assets/11019265/10522644/8cfcb298-7376-11e5-8c33-dc81e59a7529.png)

tu sta zadnja dva sklopa skrita in je "normalno", da je "vse rdeče".

**Comment by matijapretnar** [comment]
Kaj pa, če po končanem izpitu sklop skriješ, da študentje ne morejo več oddajati rešitev?

**Comment by lokarM** [comment]
Ja, imaš prav. Verjetno je potem res bolje, da so vedno prikazane vse naloge, tudi tiste, ki so skrite ...
