### ISSUE TITLE
Testiranje vhoda/izhoda

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#93]
pri

[https://www.projekt-tomo.si/problem_set/26/](https://www.projekt-tomo.si/problem_set/26/)

pri nalogi črka H imam težave. Pri Gregorju Vavdiju se je zadeva začela čudno obnašati. Ko nalogo požene, se ne izpiše čisto nič. Enostavno čez čas vrne prompt! Naloga **se shrani** na strežnik. Je rešena prav, a tega ne zazna.

In karkoli sem poskusil (naročil, naj jo potegne znova dol ...) ne dela!

Pri drugem študentu teh težav ni bilo (če gledaš log-e, se je to dogajalo danes 16. 10. okoli 13:20) 

V vsakem primeru pa ni dobro, da zaradi morebitnih čudnih testov študent ne dobi nič povratne informacije!!!

**Comment by lokarM** [comment]
Mislim, da vem zakaj gre. Verjetno je napisal funkcijo `crkaH` namesto `črkaH`  (to sem opazil še danes pri še enem). Ampak vseeno je zoprno, ker zaradi te napake enostavno študent ne dobi prav nobenega obvestila. Tudi za prvo nalogo ne. Enostavno spet prompt v IDLE ....

**Comment by lokarM** [comment]
Hm, nadaljevanje zgodbe ...
Ne vem, pri še eni študentki je IDLE (pa gre za tistega pri 3.4) "pozabil" na č-je. ENostavno se jih ne da natipkati. Tisti, ki jih potegne iz Toma, so prikazani v redu, sama pa jih ne more natipkati. 

In pri njej pri tej isti nalogi to, da bi skopira č iz navodil v ime funkcije "ne špila" ... Dobi samo proimpt brez vsakega komentarja, brez shranjevanja ...

**Comment by matijapretnar** [comment]
V pomožni funkciji `izpis` sem dodal `try` in `finally`, ki poskrbita, da se standardni izhod nastavi nazaj na običajnega. Potem se napake lepo izpišejo. Ker je ta funkcija pogosta (in v večini primerov napačno napisana brez `try`/`finally`) , bom to zadevo pustil odprto, dokler v `Check` ne definiram funkcije, ki dela to tako, kot je prav.

**Comment by matijapretnar** [comment]
V 3c4b2ad sem dodal funkciji `Check.input` in `Check.output`, ki stvari delata na bolj siguren način. Se priporočam za komentarje.
