### ISSUE TITLE
Predavanje na RTK

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#97]
Na [Sodelov@lnica - spletna skupnost učiteljev informatike in računalništva](https://skupnost.sio.si/course/view.php?id=8676) sem objavil:

=======
Spletni sistem za poučevanje programiranja
od Matija Lokar - petek, 23. oktober 2015, 12:27
 
Na Fakulteti za matematiko in fiziko smo pred kratkim zaključili prenovo sistema, ki ga uporabljamo pri poučevanju Pythona. Gre za spletno storitev, dostopno na naslovu 

                   https://www.projekt-tomo.si/ 

kjer profesor zastavi naloge (ki jih opremi s testnimi primeri), študenti pa potem te naloge rešujejo lokalno (na svojih računalnikih, v svojem okolju: IDLE, PyCharm, .... ). Gre za prenovljeno storitev https://tomo.fmf.uni-lj.si/, ki je med našimi študenti precej popularna in smo jo uspešno uporabljali v okviru različnih predmetov (a je bila dostopna le za študente FMF). 

Sistem je sedaj pripravljen tako, da ga načeloma za poučevanje kot tudi za samo učenje lahko uporablja kdorkoli. Podpira prijavo preko ARNES AAI, Facebooka in Googla. Za vlogo učitelja (torej tistega, ki skrbi za ustrezen predmet) moramo tu na FMF le ustvariti ustrezen predmet. Po prijavi imate potem možnost dodajati svoje naloge in vidite uspešnost študentov, ki se prijavijo v ta predmet (kliknejo na zvezdico ob imenu). 

Pripravljen imamo tudi vzorčni predmet, kamor postopoma dodajamo naloge, ki jih sami uporabljamo pri poučevanju. Iz tega predmeta je naloge zlahka kopirati v svoj predmet in jih potem po potrebi prilagajati. 

Če bi želeli zadevo uporabljati (kot učitelji in ne kot učenci), vas vabim, da pošljete svojo "zahtevo" na info@projekt-tomo.si. Tam navedite želeno ime predmeta. 

Seveda pa je smiselno, da prej preizkusite sistem kot učenci. Priporočam uporabo (reševanje nalog v sklopih) predmetov:

Vzorčni predmet
Prvi koraki v Python
Drugi koraki v Python

**Comment by lokarM** [comment]
K uporabi je bil vabljen tudi izr. prof, dr Janko Slavič s Fakultete za strojništvo, ki v sklopu predemta Numerične metode, letos prvič uči Python.

**Comment by lokarM** [comment]
Ko so se ravno "pridušali" o uporabnosti AAI (v povezavi z MS Office 365 in dejstva, da paradržavne izobraževalne institucije (Katis, RIC ...) "ignorirajo AAI) , sem objavil še:
...............
Tudi mi smo za svojo spletno storitev za poučevanje programiranja

       https://www.projekt-tomo.si

ki je sedaj namenjena "vsem" (ne le našim študentom, ampak komurkoli), predvideli prijavo z ArnesAAI. In dela lepo ... . Bo pa zanimivo, koliko uporabnikov se bo odločilo zanjo (možno je še Facebook in Google). Saj smo načeloma mislili uporabiti le ARNES AAI, a kaj, ko ... Je pa navedena kot prva in je večji gumb (ki ga bomo še povečali ;-) )

**Comment by lokarM** [comment]
NA današnjem sestanku v povezavi [s tekmovanjem rtk](http://rtk.ijs.si/), ki bo v soboto 19. 3. 2016, so me "zadolžili", da za mentorje pripravim dobro uro dolgo predavanje o sistemu Tomo. Računamo na udeležbo cca. 20-30 učiteljev s srednjih šol, ki so mentorji tekmovalcem v programiranju, torej dejansko potencialni kandidati za "naše učitelje": Lepo bi bilo, če bi za ta dan še kdo drug @matijapretnar , @gregorjerse načrtoval, da bi bil zraven ...

**Comment by gregorjerse** [comment]
Jaz sem z veseljem zraven.

Lp,
Gregor

lokarM <notifications@github.com> je napisal:

**Comment by matijapretnar** [comment]
Jaz se ravno tisti (ali pa prejšnji dan) vrnem iz enotedenske delavnice v Nemčiji, tako da moram še malo preveriti pri domačih, koliko bodo navdušeni. Lahko pa seveda pomagam pri pripravi.
