### ISSUE TITLE
Pregled študentskih rešitev

### ISSUE THREAD

**Issue by lokarM** [matijapretnar/projekt-tomo#98]
Zdi se mi malo nelogično:
* ko kliknem na Pie charte me vrže na besedilo naloge
* ko kliknem na ime naloge, me vrže na pregledni seznam vseh rešitev

Zdi se mi, da bi moralo biti ravno obratno

**Comment by lokarM** [comment]
@matijapretnar  - bi se dalo tole popraviti (ker dejansko gre po moje le za zamenjavo dveh vrstic). Ne vem - nikakor se ne morem anvaditi na tako obnašanje - hočem besedilo naloge in vedno kliknem na ime naloge, namesto na piechart. Potem nekaj trenutkov delam "prav", potem pa me spet zapelje moja napačna (po moje pravilna, logična, a ...) predstava.

Kaj pa menite ostali?

**Comment by matijapretnar** [comment]
Urejeno. Čez par minut bo tudi delalo tudi v živo.
