### ISSUE TITLE
Nenavadni fonti v brskalniku Firefox

### ISSUE THREAD

**Issue by nbasic** [matijapretnar/projekt-tomo#99]
V brskalniku Mozilla Firefox 41.0.2 na operacijskem sistemu Ubuntu 14.04.3 LTS so uporabljeni neki čudni fonti. Še posebej grde so črke `v`, `N`, `M`, `A` in `č`:

![weird-fonts](https://cloud.githubusercontent.com/assets/5173260/10755297/0a7cb59a-7c9d-11e5-97e1-29b3ecf76330.png)

**Comment by matijapretnar** [comment]
@nbasic - ali lahko malo bolj raziščeš, kje je težava, npr. ali se kakšen font ne naloži in podobno.

**Comment by mrcinv** [comment]
Podobne težave imam v eni verziji Firefoxa tudi jaz. Firefox besedilo očitno prikaže s fontom Lato Hairline, ki je neberljiv.
![zaslonska slika 2015-12-15 14 33 18](https://cloud.githubusercontent.com/assets/5948013/11811939/e1b5841c-a338-11e5-9fd4-01fe6a78fa56.png)
![zaslonska slika 2015-12-15 14 33 39](https://cloud.githubusercontent.com/assets/5948013/11811942/eaacb18a-a338-11e5-8feb-7fc02d462e7f.png)

**Comment by mrcinv** [comment]
Gre za Firefox 42.0 na "Ubuntu 14.04.3 LTS". Na Ubuntu 15.10 in Chrome, tega problema ni.

**Comment by mrcinv** [comment]
Zanimivo, da mi na "Ubuntu 15.10" Firefox za Lato font izbere "Lato Light".

**Comment by matijapretnar** [comment]
@nbasic, ali lahko to stvar urediš ti, glede na to, da imaš Ubuntu?

**Comment by strelec** [comment]
Kakor vidim, si dejansko pisave "Lato" v tem projektu sploh ne želite, ker je pretanka za tako majhen tekst in sploh nima šumnikov.

Ker Windows in Mac pisave Lato nimata, uporabita neko drugo sans-serifno pisavo, Ubunutu pa jo ima, zato jo uporabi, kar pomeni zgornja dva problema. Glejte pull request.

https://github.com/matijapretnar/projekt-tomo/pull/133

**Comment by matijapretnar** [comment]
Super, najlepša hvala!
